# Notebook 09 - Uncertainty Quantification (Second version)

City-agnostic improved workflow for **Rome**. This version keeps the
original March 2026 `NB09` untouched and adds three targeted
improvements: 

- spatially explicit daily raster modifiers for trees and
waste heat

- event-level warning-day logic for EWS

- EWS CBA uncertainty
outputs alongside the impact uncertainty outputs

All new outputs are written to
`outputs/rome/tables/uncertainty_improved/` so the original `NB09`
outputs remain unchanged.

In [1]:
import os
import sys
from pathlib import Path

os.environ.setdefault('CITY', 'rome')
os.environ.setdefault('NB09_N', '512')
os.environ.setdefault('NB09_SEED', '42')

def _find_repo_root():
    env = os.environ.get("URBAN_HEAT_ROOT")
    if env:
        root = Path(env).expanduser().resolve()
        if (root / "cityheat").is_dir() and (root / "configs").is_dir():
            return root
    start = Path.cwd().resolve()
    for cand in [start, *start.parents]:
        if (cand / "cityheat").is_dir() and (cand / "configs").is_dir():
            return cand
    raise RuntimeError(
        "Could not locate repo root. Run the notebook from inside the repo "
        "or set URBAN_HEAT_ROOT."
    )

ROOT = _find_repo_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print('ROOT:', ROOT)
print('CITY:', os.environ['CITY'])
print('NB09_N:', os.environ['NB09_N'])
print('NB09_SEED:', os.environ['NB09_SEED'])

ROOT: /Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat
CITY: rome
NB09_N: 512
NB09_SEED: 42

In [2]:
from cityheat.nb09_improved import run_nb09_improved

paths = run_nb09_improved()
paths

Matplotlib is building the font cache; this may take a moment.

[rome] sample 1/512: year=2050 aai=1.914

[rome] sample 2/512: year=2030 aai=0.450

[rome] sample 3/512: year=2040 aai=1.333

[rome] sample 4/512: year=2020 aai=0.029

[rome] sample 5/512: year=2020 aai=1.518

[rome] sample 6/512: year=2030 aai=0.421

[rome] sample 7/512: year=2040 aai=0.546

[rome] sample 8/512: year=2050 aai=0.069

[rome] sample 9/512: year=2020 aai=0.920

[rome] sample 10/512: year=2040 aai=0.675

[rome] sample 11/512: year=2040 aai=0.166

[rome] sample 12/512: year=2020 aai=0.163

[rome] sample 13/512: year=2040 aai=0.106

[rome] sample 14/512: year=2020 aai=1.129

[rome] sample 15/512: year=2040 aai=2.695

[rome] sample 16/512: year=2050 aai=0.159

[rome] sample 17/512: year=2020 aai=1.609

[rome] sample 18/512: year=2050 aai=0.149

[rome] sample 19/512: year=2040 aai=1.810

[rome] sample 20/512: year=2020 aai=0.327

[rome] sample 21/512: year=2020 aai=1.600

[rome] sample 22/512: year=2050 aai=0.076

[rome] sample 23/512: year=2020 aai=0.714

[rome] sample 24/512: year=2030 aai=0.537

[rome] sample 25/512: year=2050 aai=0.979

[rome] sample 26/512: year=2030 aai=0.649

[rome] sample 27/512: year=2020 aai=0.049

[rome] sample 28/512: year=2050 aai=1.186

[rome] sample 29/512: year=2030 aai=0.720

[rome] sample 30/512: year=2030 aai=0.622

[rome] sample 31/512: year=2020 aai=1.088

[rome] sample 32/512: year=2030 aai=0.553

[rome] sample 33/512: year=2020 aai=0.953

[rome] sample 34/512: year=2020 aai=1.118

[rome] sample 35/512: year=2040 aai=0.121

[rome] sample 36/512: year=2040 aai=1.211

[rome] sample 37/512: year=2040 aai=0.096

[rome] sample 38/512: year=2050 aai=2.361

[rome] sample 39/512: year=2040 aai=1.203

[rome] sample 40/512: year=2050 aai=1.298

[rome] sample 41/512: year=2030 aai=0.149

[rome] sample 42/512: year=2020 aai=1.193

[rome] sample 43/512: year=2020 aai=0.254

[rome] sample 44/512: year=2040 aai=0.504

[rome] sample 45/512: year=2050 aai=0.464

[rome] sample 46/512: year=2050 aai=0.368

[rome] sample 47/512: year=2040 aai=0.891

[rome] sample 48/512: year=2040 aai=0.126

[rome] sample 49/512: year=2030 aai=0.301

[rome] sample 50/512: year=2040 aai=0.792

[rome] sample 51/512: year=2020 aai=0.002

[rome] sample 52/512: year=2050 aai=0.805

[rome] sample 53/512: year=2040 aai=2.232

[rome] sample 54/512: year=2020 aai=0.281

[rome] sample 55/512: year=2050 aai=1.547

[rome] sample 56/512: year=2040 aai=0.649

[rome] sample 57/512: year=2030 aai=0.838

[rome] sample 58/512: year=2020 aai=0.658

[rome] sample 59/512: year=2020 aai=0.467

[rome] sample 60/512: year=2040 aai=0.003

[rome] sample 61/512: year=2040 aai=0.598

[rome] sample 62/512: year=2050 aai=3.160

[rome] sample 63/512: year=2050 aai=0.271

[rome] sample 64/512: year=2040 aai=1.400

[rome] sample 65/512: year=2020 aai=0.261

[rome] sample 66/512: year=2030 aai=1.299

[rome] sample 67/512: year=2030 aai=1.196

[rome] sample 68/512: year=2050 aai=0.146

[rome] sample 69/512: year=2020 aai=0.110

[rome] sample 70/512: year=2040 aai=0.005

[rome] sample 71/512: year=2050 aai=1.399

[rome] sample 72/512: year=2030 aai=0.324

[rome] sample 73/512: year=2030 aai=0.135

[rome] sample 74/512: year=2030 aai=1.517

[rome] sample 75/512: year=2020 aai=0.130

[rome] sample 76/512: year=2020 aai=1.220

[rome] sample 77/512: year=2020 aai=0.002

[rome] sample 78/512: year=2050 aai=0.911

[rome] sample 79/512: year=2050 aai=0.055

[rome] sample 80/512: year=2050 aai=0.421

[rome] sample 81/512: year=2020 aai=1.010

[rome] sample 82/512: year=2050 aai=1.132

[rome] sample 83/512: year=2020 aai=0.249

[rome] sample 84/512: year=2020 aai=0.043

[rome] sample 85/512: year=2050 aai=0.073

[rome] sample 86/512: year=2050 aai=1.347

[rome] sample 87/512: year=2050 aai=0.735

[rome] sample 88/512: year=2020 aai=0.943

[rome] sample 89/512: year=2040 aai=2.605

[rome] sample 90/512: year=2040 aai=0.091

[rome] sample 91/512: year=2020 aai=0.027

[rome] sample 92/512: year=2030 aai=0.006

[rome] sample 93/512: year=2030 aai=0.680

[rome] sample 94/512: year=2030 aai=0.391

[rome] sample 95/512: year=2030 aai=0.102

[rome] sample 96/512: year=2020 aai=0.021

[rome] sample 97/512: year=2050 aai=0.882

[rome] sample 98/512: year=2030 aai=0.027

[rome] sample 99/512: year=2040 aai=0.626

[rome] sample 100/512: year=2020 aai=0.315

[rome] sample 101/512: year=2030 aai=0.049

[rome] sample 102/512: year=2040 aai=0.811

[rome] sample 103/512: year=2040 aai=0.003

[rome] sample 104/512: year=2030 aai=0.451

[rome] sample 105/512: year=2030 aai=0.488

[rome] sample 106/512: year=2050 aai=0.095

[rome] sample 107/512: year=2020 aai=0.215

[rome] sample 108/512: year=2040 aai=0.489

[rome] sample 109/512: year=2050 aai=0.301

[rome] sample 110/512: year=2020 aai=0.411

[rome] sample 111/512: year=2040 aai=0.207

[rome] sample 112/512: year=2030 aai=0.311

[rome] sample 113/512: year=2020 aai=0.512

[rome] sample 114/512: year=2030 aai=0.539

[rome] sample 115/512: year=2020 aai=0.945

[rome] sample 116/512: year=2050 aai=0.931

[rome] sample 117/512: year=2030 aai=0.116

[rome] sample 118/512: year=2050 aai=0.434

[rome] sample 119/512: year=2030 aai=1.556

[rome] sample 120/512: year=2020 aai=0.322

[rome] sample 121/512: year=2020 aai=1.507

[rome] sample 122/512: year=2040 aai=2.836

[rome] sample 123/512: year=2030 aai=0.273

[rome] sample 124/512: year=2040 aai=0.154

[rome] sample 125/512: year=2020 aai=1.291

[rome] sample 126/512: year=2020 aai=0.599

[rome] sample 127/512: year=2040 aai=1.142

[rome] sample 128/512: year=2030 aai=0.058

[rome] sample 129/512: year=2030 aai=0.679

[rome] sample 130/512: year=2020 aai=1.290

[rome] sample 131/512: year=2030 aai=0.059

[rome] sample 132/512: year=2050 aai=0.739

[rome] sample 133/512: year=2030 aai=0.172

[rome] sample 134/512: year=2050 aai=0.189

[rome] sample 135/512: year=2040 aai=0.863

[rome] sample 136/512: year=2030 aai=1.807

[rome] sample 137/512: year=2050 aai=2.860

[rome] sample 138/512: year=2020 aai=0.227

[rome] sample 139/512: year=2020 aai=0.929

[rome] sample 140/512: year=2050 aai=0.065

[rome] sample 141/512: year=2030 aai=0.141

[rome] sample 142/512: year=2020 aai=0.781

[rome] sample 143/512: year=2040 aai=0.046

[rome] sample 144/512: year=2050 aai=1.533

[rome] sample 145/512: year=2020 aai=0.042

[rome] sample 146/512: year=2030 aai=0.082

[rome] sample 147/512: year=2050 aai=0.655

[rome] sample 148/512: year=2020 aai=0.099

[rome] sample 149/512: year=2020 aai=0.251

[rome] sample 150/512: year=2030 aai=1.496

[rome] sample 151/512: year=2040 aai=1.077

[rome] sample 152/512: year=2040 aai=1.721

[rome] sample 153/512: year=2030 aai=0.003

[rome] sample 154/512: year=2050 aai=0.837

[rome] sample 155/512: year=2020 aai=0.107

[rome] sample 156/512: year=2020 aai=0.288

[rome] sample 157/512: year=2040 aai=0.072

[rome] sample 158/512: year=2050 aai=0.350

[rome] sample 159/512: year=2050 aai=0.267

[rome] sample 160/512: year=2040 aai=1.030

[rome] sample 161/512: year=2040 aai=0.762

[rome] sample 162/512: year=2050 aai=0.991

[rome] sample 163/512: year=2040 aai=0.372

[rome] sample 164/512: year=2030 aai=3.103

[rome] sample 165/512: year=2030 aai=1.239

[rome] sample 166/512: year=2030 aai=1.957

[rome] sample 167/512: year=2050 aai=0.353

[rome] sample 168/512: year=2040 aai=0.392

[rome] sample 169/512: year=2040 aai=1.007

[rome] sample 170/512: year=2050 aai=0.127

[rome] sample 171/512: year=2020 aai=0.394

[rome] sample 172/512: year=2040 aai=0.318

[rome] sample 173/512: year=2020 aai=0.604

[rome] sample 174/512: year=2030 aai=0.067

[rome] sample 175/512: year=2040 aai=0.037

[rome] sample 176/512: year=2030 aai=0.817

[rome] sample 177/512: year=2040 aai=0.262

[rome] sample 178/512: year=2040 aai=0.886

[rome] sample 179/512: year=2050 aai=0.064

[rome] sample 180/512: year=2050 aai=2.568

[rome] sample 181/512: year=2050 aai=0.075

[rome] sample 182/512: year=2020 aai=0.136

[rome] sample 183/512: year=2040 aai=0.158

[rome] sample 184/512: year=2020 aai=0.201

[rome] sample 185/512: year=2030 aai=0.187

[rome] sample 186/512: year=2040 aai=0.659

[rome] sample 187/512: year=2040 aai=3.214

[rome] sample 188/512: year=2040 aai=0.145

[rome] sample 189/512: year=2030 aai=0.353

[rome] sample 190/512: year=2030 aai=1.060

[rome] sample 191/512: year=2030 aai=0.357

[rome] sample 192/512: year=2040 aai=0.813

[rome] sample 193/512: year=2020 aai=0.493

[rome] sample 194/512: year=2030 aai=0.764

[rome] sample 195/512: year=2020 aai=0.317

[rome] sample 196/512: year=2050 aai=2.308

[rome] sample 197/512: year=2020 aai=2.132

[rome] sample 198/512: year=2020 aai=0.044

[rome] sample 199/512: year=2050 aai=0.594

[rome] sample 200/512: year=2040 aai=0.058

[rome] sample 201/512: year=2050 aai=0.229

[rome] sample 202/512: year=2030 aai=0.079

[rome] sample 203/512: year=2020 aai=0.004

[rome] sample 204/512: year=2050 aai=1.378

[rome] sample 205/512: year=2040 aai=0.777

[rome] sample 206/512: year=2020 aai=0.687

[rome] sample 207/512: year=2040 aai=0.035

[rome] sample 208/512: year=2030 aai=0.055

[rome] sample 209/512: year=2020 aai=0.005

[rome] sample 210/512: year=2030 aai=1.946

[rome] sample 211/512: year=2030 aai=0.170

[rome] sample 212/512: year=2050 aai=0.011

[rome] sample 213/512: year=2040 aai=0.204

[rome] sample 214/512: year=2040 aai=0.792

[rome] sample 215/512: year=2030 aai=0.031

[rome] sample 216/512: year=2030 aai=0.163

[rome] sample 217/512: year=2020 aai=0.020

[rome] sample 218/512: year=2020 aai=0.560

[rome] sample 219/512: year=2020 aai=1.704

[rome] sample 220/512: year=2050 aai=0.065

[rome] sample 221/512: year=2050 aai=0.903

[rome] sample 222/512: year=2040 aai=0.313

[rome] sample 223/512: year=2040 aai=0.052

[rome] sample 224/512: year=2040 aai=0.191

[rome] sample 225/512: year=2050 aai=0.462

[rome] sample 226/512: year=2020 aai=2.460

[rome] sample 227/512: year=2030 aai=0.150

[rome] sample 228/512: year=2030 aai=0.759

[rome] sample 229/512: year=2040 aai=0.390

[rome] sample 230/512: year=2050 aai=0.377

[rome] sample 231/512: year=2030 aai=0.103

[rome] sample 232/512: year=2050 aai=0.179

[rome] sample 233/512: year=2030 aai=2.298

[rome] sample 234/512: year=2020 aai=0.618

[rome] sample 235/512: year=2020 aai=0.029

[rome] sample 236/512: year=2050 aai=0.038

[rome] sample 237/512: year=2050 aai=2.166

[rome] sample 238/512: year=2020 aai=0.547

[rome] sample 239/512: year=2040 aai=0.795

[rome] sample 240/512: year=2050 aai=0.007

[rome] sample 241/512: year=2040 aai=0.549

[rome] sample 242/512: year=2040 aai=0.165

[rome] sample 243/512: year=2030 aai=0.204

[rome] sample 244/512: year=2040 aai=0.455

[rome] sample 245/512: year=2050 aai=0.223

[rome] sample 246/512: year=2050 aai=0.689

[rome] sample 247/512: year=2040 aai=0.002

[rome] sample 248/512: year=2020 aai=1.803

[rome] sample 249/512: year=2030 aai=1.928

[rome] sample 250/512: year=2040 aai=0.145

[rome] sample 251/512: year=2050 aai=0.003

[rome] sample 252/512: year=2030 aai=0.020

[rome] sample 253/512: year=2020 aai=0.044

[rome] sample 254/512: year=2050 aai=0.083

[rome] sample 255/512: year=2040 aai=0.042

[rome] sample 256/512: year=2040 aai=0.791

[rome] sample 257/512: year=2020 aai=0.219

[rome] sample 258/512: year=2020 aai=0.811

[rome] sample 259/512: year=2030 aai=0.053

[rome] sample 260/512: year=2040 aai=0.130

[rome] sample 261/512: year=2020 aai=0.144

[rome] sample 262/512: year=2050 aai=0.294

[rome] sample 263/512: year=2050 aai=0.519

[rome] sample 264/512: year=2020 aai=0.936

[rome] sample 265/512: year=2020 aai=0.279

[rome] sample 266/512: year=2050 aai=0.335

[rome] sample 267/512: year=2030 aai=0.734

[rome] sample 268/512: year=2030 aai=0.191

[rome] sample 269/512: year=2020 aai=0.076

[rome] sample 270/512: year=2040 aai=0.067

[rome] sample 271/512: year=2050 aai=1.557

[rome] sample 272/512: year=2040 aai=0.893

[rome] sample 273/512: year=2040 aai=0.003

[rome] sample 274/512: year=2040 aai=1.581

[rome] sample 275/512: year=2030 aai=0.158

[rome] sample 276/512: year=2030 aai=0.211

[rome] sample 277/512: year=2040 aai=0.347

[rome] sample 278/512: year=2020 aai=0.341

[rome] sample 279/512: year=2020 aai=0.028

[rome] sample 280/512: year=2050 aai=1.970

[rome] sample 281/512: year=2050 aai=1.558

[rome] sample 282/512: year=2030 aai=1.381

[rome] sample 283/512: year=2020 aai=0.029

[rome] sample 284/512: year=2020 aai=0.034

[rome] sample 285/512: year=2040 aai=0.243

[rome] sample 286/512: year=2030 aai=0.742

[rome] sample 287/512: year=2030 aai=1.287

[rome] sample 288/512: year=2030 aai=0.002

[rome] sample 289/512: year=2040 aai=0.477

[rome] sample 290/512: year=2050 aai=0.052

[rome] sample 291/512: year=2040 aai=0.110

[rome] sample 292/512: year=2050 aai=0.529

[rome] sample 293/512: year=2030 aai=0.044

[rome] sample 294/512: year=2050 aai=1.926

[rome] sample 295/512: year=2040 aai=0.831

[rome] sample 296/512: year=2020 aai=0.123

[rome] sample 297/512: year=2050 aai=0.205

[rome] sample 298/512: year=2040 aai=0.185

[rome] sample 299/512: year=2040 aai=0.341

[rome] sample 300/512: year=2020 aai=0.271

[rome] sample 301/512: year=2050 aai=1.786

[rome] sample 302/512: year=2050 aai=0.090

[rome] sample 303/512: year=2040 aai=0.078

[rome] sample 304/512: year=2030 aai=0.443

[rome] sample 305/512: year=2020 aai=0.213

[rome] sample 306/512: year=2030 aai=0.025

[rome] sample 307/512: year=2040 aai=0.680

[rome] sample 308/512: year=2050 aai=0.770

[rome] sample 309/512: year=2030 aai=0.186

[rome] sample 310/512: year=2030 aai=0.048

[rome] sample 311/512: year=2020 aai=0.387

[rome] sample 312/512: year=2020 aai=0.041

[rome] sample 313/512: year=2030 aai=1.076

[rome] sample 314/512: year=2050 aai=0.053

[rome] sample 315/512: year=2020 aai=0.907

[rome] sample 316/512: year=2040 aai=1.973

[rome] sample 317/512: year=2040 aai=0.170

[rome] sample 318/512: year=2040 aai=0.265

[rome] sample 319/512: year=2040 aai=0.668

[rome] sample 320/512: year=2040 aai=0.679

[rome] sample 321/512: year=2050 aai=0.083

[rome] sample 322/512: year=2040 aai=0.100

[rome] sample 323/512: year=2040 aai=0.266

[rome] sample 324/512: year=2040 aai=0.047

[rome] sample 325/512: year=2030 aai=1.626

[rome] sample 326/512: year=2040 aai=0.033

[rome] sample 327/512: year=2030 aai=0.455

[rome] sample 328/512: year=2050 aai=0.030

[rome] sample 329/512: year=2040 aai=0.080

[rome] sample 330/512: year=2040 aai=0.076

[rome] sample 331/512: year=2030 aai=0.189

[rome] sample 332/512: year=2050 aai=0.060

[rome] sample 333/512: year=2030 aai=0.274

[rome] sample 334/512: year=2030 aai=0.004

[rome] sample 335/512: year=2020 aai=0.259

[rome] sample 336/512: year=2040 aai=0.173

[rome] sample 337/512: year=2050 aai=0.057

[rome] sample 338/512: year=2040 aai=3.505

[rome] sample 339/512: year=2040 aai=0.138

[rome] sample 340/512: year=2020 aai=0.002

[rome] sample 341/512: year=2020 aai=0.094

[rome] sample 342/512: year=2030 aai=0.686

[rome] sample 343/512: year=2040 aai=0.199

[rome] sample 344/512: year=2050 aai=0.067

[rome] sample 345/512: year=2020 aai=1.374

[rome] sample 346/512: year=2050 aai=0.043

[rome] sample 347/512: year=2050 aai=0.777

[rome] sample 348/512: year=2030 aai=1.244

[rome] sample 349/512: year=2020 aai=0.128

[rome] sample 350/512: year=2030 aai=1.016

[rome] sample 351/512: year=2030 aai=1.254

[rome] sample 352/512: year=2020 aai=0.122

[rome] sample 353/512: year=2030 aai=0.291

[rome] sample 354/512: year=2050 aai=0.490

[rome] sample 355/512: year=2020 aai=0.122

[rome] sample 356/512: year=2030 aai=0.043

[rome] sample 357/512: year=2050 aai=2.106

[rome] sample 358/512: year=2020 aai=0.068

[rome] sample 359/512: year=2050 aai=0.095

[rome] sample 360/512: year=2030 aai=0.802

[rome] sample 361/512: year=2020 aai=0.084

[rome] sample 362/512: year=2020 aai=0.270

[rome] sample 363/512: year=2030 aai=0.097

[rome] sample 364/512: year=2030 aai=0.662

[rome] sample 365/512: year=2020 aai=0.605

[rome] sample 366/512: year=2040 aai=0.555

[rome] sample 367/512: year=2020 aai=0.478

[rome] sample 368/512: year=2030 aai=0.206

[rome] sample 369/512: year=2030 aai=0.049

[rome] sample 370/512: year=2020 aai=0.702

[rome] sample 371/512: year=2050 aai=0.092

[rome] sample 372/512: year=2050 aai=0.800

[rome] sample 373/512: year=2020 aai=0.425

[rome] sample 374/512: year=2020 aai=0.239

[rome] sample 375/512: year=2030 aai=0.167

[rome] sample 376/512: year=2020 aai=0.300

[rome] sample 377/512: year=2050 aai=0.104

[rome] sample 378/512: year=2020 aai=0.249

[rome] sample 379/512: year=2020 aai=1.083

[rome] sample 380/512: year=2030 aai=0.507

[rome] sample 381/512: year=2040 aai=0.564

[rome] sample 382/512: year=2020 aai=0.127

[rome] sample 383/512: year=2020 aai=0.067

[rome] sample 384/512: year=2050 aai=0.389

[rome] sample 385/512: year=2040 aai=0.269

[rome] sample 386/512: year=2030 aai=0.399

[rome] sample 387/512: year=2050 aai=1.172

[rome] sample 388/512: year=2020 aai=0.004

[rome] sample 389/512: year=2030 aai=0.240

[rome] sample 390/512: year=2040 aai=0.353

[rome] sample 391/512: year=2050 aai=0.644

[rome] sample 392/512: year=2050 aai=0.200

[rome] sample 393/512: year=2020 aai=0.138

[rome] sample 394/512: year=2050 aai=0.122

[rome] sample 395/512: year=2050 aai=0.819

[rome] sample 396/512: year=2020 aai=0.355

[rome] sample 397/512: year=2030 aai=0.091

[rome] sample 398/512: year=2050 aai=1.933

[rome] sample 399/512: year=2030 aai=0.132

[rome] sample 400/512: year=2020 aai=0.107

[rome] sample 401/512: year=2030 aai=0.004

[rome] sample 402/512: year=2040 aai=1.173

[rome] sample 403/512: year=2050 aai=3.110

[rome] sample 404/512: year=2030 aai=0.002

[rome] sample 405/512: year=2030 aai=0.225

[rome] sample 406/512: year=2030 aai=0.199

[rome] sample 407/512: year=2050 aai=0.049

[rome] sample 408/512: year=2050 aai=0.151

[rome] sample 409/512: year=2040 aai=0.669

[rome] sample 410/512: year=2050 aai=0.162

[rome] sample 411/512: year=2050 aai=0.352

[rome] sample 412/512: year=2050 aai=0.017

[rome] sample 413/512: year=2040 aai=0.663

[rome] sample 414/512: year=2050 aai=0.997

[rome] sample 415/512: year=2050 aai=1.523

[rome] sample 416/512: year=2040 aai=0.730

[rome] sample 417/512: year=2050 aai=0.756

[rome] sample 418/512: year=2030 aai=0.729

[rome] sample 419/512: year=2030 aai=0.077

[rome] sample 420/512: year=2030 aai=0.164

[rome] sample 421/512: year=2050 aai=0.428

[rome] sample 422/512: year=2030 aai=1.717

[rome] sample 423/512: year=2030 aai=1.694

[rome] sample 424/512: year=2050 aai=0.539

[rome] sample 425/512: year=2050 aai=1.237

[rome] sample 426/512: year=2050 aai=1.748

[rome] sample 427/512: year=2050 aai=0.163

[rome] sample 428/512: year=2050 aai=0.024

[rome] sample 429/512: year=2040 aai=0.910

[rome] sample 430/512: year=2050 aai=0.262

[rome] sample 431/512: year=2030 aai=0.371

[rome] sample 432/512: year=2050 aai=0.003

[rome] sample 433/512: year=2020 aai=1.145

[rome] sample 434/512: year=2040 aai=1.396

[rome] sample 435/512: year=2040 aai=0.049

[rome] sample 436/512: year=2030 aai=0.436

[rome] sample 437/512: year=2030 aai=0.003

[rome] sample 438/512: year=2020 aai=0.127

[rome] sample 439/512: year=2050 aai=0.275

[rome] sample 440/512: year=2030 aai=0.109

[rome] sample 441/512: year=2020 aai=1.921

[rome] sample 442/512: year=2020 aai=0.223

[rome] sample 443/512: year=2030 aai=0.167

[rome] sample 444/512: year=2020 aai=1.043

[rome] sample 445/512: year=2050 aai=0.228

[rome] sample 446/512: year=2040 aai=0.013

[rome] sample 447/512: year=2040 aai=0.064

[rome] sample 448/512: year=2040 aai=1.363

[rome] sample 449/512: year=2030 aai=0.027

[rome] sample 450/512: year=2030 aai=0.263

[rome] sample 451/512: year=2050 aai=0.041

[rome] sample 452/512: year=2050 aai=0.004

[rome] sample 453/512: year=2040 aai=1.277

[rome] sample 454/512: year=2030 aai=0.079

[rome] sample 455/512: year=2050 aai=0.254

[rome] sample 456/512: year=2030 aai=0.039

[rome] sample 457/512: year=2020 aai=0.453

[rome] sample 458/512: year=2040 aai=1.086

[rome] sample 459/512: year=2020 aai=0.549

[rome] sample 460/512: year=2050 aai=0.101

[rome] sample 461/512: year=2030 aai=0.140

[rome] sample 462/512: year=2050 aai=0.244

[rome] sample 463/512: year=2040 aai=1.238

[rome] sample 464/512: year=2050 aai=0.418

[rome] sample 465/512: year=2020 aai=0.150

[rome] sample 466/512: year=2020 aai=0.589

[rome] sample 467/512: year=2040 aai=1.550

[rome] sample 468/512: year=2020 aai=0.003

[rome] sample 469/512: year=2040 aai=0.103

[rome] sample 470/512: year=2050 aai=1.277

[rome] sample 471/512: year=2040 aai=0.629

[rome] sample 472/512: year=2020 aai=1.232

[rome] sample 473/512: year=2050 aai=0.811

[rome] sample 474/512: year=2020 aai=0.018

[rome] sample 475/512: year=2020 aai=0.251

[rome] sample 476/512: year=2030 aai=0.344

[rome] sample 477/512: year=2030 aai=1.108

[rome] sample 478/512: year=2030 aai=0.553

[rome] sample 479/512: year=2050 aai=0.099

[rome] sample 480/512: year=2030 aai=1.484

[rome] sample 481/512: year=2050 aai=0.097

[rome] sample 482/512: year=2030 aai=0.011

[rome] sample 483/512: year=2040 aai=0.333

[rome] sample 484/512: year=2040 aai=0.171

[rome] sample 485/512: year=2020 aai=0.304

[rome] sample 486/512: year=2040 aai=0.018

[rome] sample 487/512: year=2050 aai=0.076

[rome] sample 488/512: year=2020 aai=0.083

[rome] sample 489/512: year=2030 aai=0.314

[rome] sample 490/512: year=2040 aai=0.353

[rome] sample 491/512: year=2020 aai=1.230

[rome] sample 492/512: year=2030 aai=0.566

[rome] sample 493/512: year=2040 aai=0.701

[rome] sample 494/512: year=2020 aai=0.667

[rome] sample 495/512: year=2040 aai=1.555

[rome] sample 496/512: year=2020 aai=0.001

[rome] sample 497/512: year=2050 aai=0.596

[rome] sample 498/512: year=2030 aai=2.385

[rome] sample 499/512: year=2020 aai=0.112

[rome] sample 500/512: year=2050 aai=1.119

[rome] sample 501/512: year=2040 aai=0.553

[rome] sample 502/512: year=2050 aai=0.003

[rome] sample 503/512: year=2040 aai=1.590

[rome] sample 504/512: year=2020 aai=0.004

[rome] sample 505/512: year=2030 aai=0.093

[rome] sample 506/512: year=2030 aai=0.178

[rome] sample 507/512: year=2040 aai=0.036

[rome] sample 508/512: year=2040 aai=0.709

[rome] sample 509/512: year=2040 aai=0.161

[rome] sample 510/512: year=2030 aai=0.034

[rome] sample 511/512: year=2040 aai=0.958

[rome] sample 512/512: year=2030 aai=0.024

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))
/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))
/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

{'samples': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_samples_rome_improved.csv'),
 'impact': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_impact_summary_rome_improved.csv'),
 'freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_freq_curve_rome_improved.csv'),
 'cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_cba_ews_rome_improved.csv'),
 'vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_vulnerability_rome_improved.csv'),
 'sens_aai': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_aai_agg_rome_improved.csv'),
 'sens_freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_freq_curve_rome_improved.csv'),
 'sens_cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_cba_ews_rome_improved.csv'),
 'sens_vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_vulnerability_rome_improved.csv'),
 'meta': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/uq_dimensions_rome_improved.json'),
 'bundle': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_impact_rome_march2026_improved.h5'),
 'bundle_sens': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_impact_rome_march2026_improved_with_sensitivity.h5')}

In [3]:
import pandas as pd

samples = pd.read_csv(paths['samples'])
samples[[
    'year', 'aai_agg', 'annual_deaths', 'sample_warning_days',
    'sample_threshold_deaths_per_day', 'ews_pv_cost_25y',
    'ews_net_avoided_deaths_25y_cum', 'ews_cost_per_net_death_25y_cum'
]].head(10)

,year,aai_agg,annual_deaths,sample_warning_days,sample_threshold_deaths_per_day,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_cost_per_net_death_25y_cum
0,2050,1.913913,698.578330,46.0,6.605830,2.029123e+06,598.754228,3388.908677
1,2030,0.450388,164.391528,48.0,1.600121,2.628930e+07,602.127765,43660.669232
2,2040,1.332927,487.851293,36.0,5.979293,1.714664e+07,402.190189,42633.151924
3,2020,0.028764,10.527716,23.0,0.142691,1.522767e+07,64.037682,237792.327713
4,2020,1.518003,555.588927,30.0,5.754208,4.636326e+06,2724.427677,1701.761618
5,2030,0.420548,153.500070,23.0,2.168037,1.431346e+07,83.102473,172238.664194
6,2040,0.546384,199.976471,53.0,1.801049,2.689060e+07,589.117214,45645.590788
7,2050,0.068603,25.040137,51.0,0.092392,1.729132e+07,55.804500,309855.275692
8,2020,0.919558,336.558163,15.0,5.443878,1.308399e+07,402.537516,32503.783043
9,2040,0.674828,246.987199,21.0,4.083801,7.947683e+06,535.995193,14827.900229

In [4]:
impact_summary = pd.read_csv(paths['impact'])
cba_summary = pd.read_csv(paths['cba'])

display(impact_summary.describe())
display(cba_summary.describe())

,aai_agg,annual_deaths,rp2,rp5,rp10,rp20
count,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000
mean,0.579527,211.811082,0.007936,1.019449,2.090256,2.931049
std,0.642023,234.625122,0.047779,1.429089,2.266364,2.958164
min,0.001271,0.465215,0.000000,0.000000,0.000022,0.000911
25%,0.103094,37.676428,0.000000,0.027663,0.357529,0.601321
50%,0.329809,120.709957,0.000000,0.424545,1.221654,1.859588
75%,0.817177,298.269731,0.000000,1.579636,3.141346,4.309646
max,3.504952,1282.812264,0.509485,8.507980,10.714316,13.320821

,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_net_avoided_deaths_25y_pv,ews_cost_per_net_death_25y_cum,ews_cost_per_net_death_25y_pv,ews_life_years_saved_25y_cum
count,5.120000e+02,512.000000,512.000000,5.120000e+02,5.120000e+02,512.000000
mean,9.947900e+06,332.429337,217.082468,3.012825e+05,4.665087e+05,4332.492234
std,7.918570e+06,442.437512,288.584714,1.253889e+06,1.943517e+06,5831.585059
min,1.138022e+06,0.701840,0.441585,1.216758e+03,1.857089e+03,8.936871
25%,3.218236e+06,61.884901,40.495267,1.513015e+04,2.345274e+04,809.296777
50%,5.986729e+06,170.011583,111.109859,4.070360e+04,6.195708e+04,2214.348246
75%,1.666296e+07,449.367461,290.603474,1.398476e+05,2.124164e+05,5731.926204
max,3.178834e+07,2859.781083,1873.718584,1.536912e+07,2.435294e+07,36707.296717