# Notebook 09 - Uncertainty Quantification (Second version)

City-agnostic improved workflow for **Rome**. This version keeps the original March 2026 `NB09` untouched and adds three targeted improvements:
- spatially explicit daily raster modifiers for trees and waste heat
- event-level warning-day logic for EWS
- EWS CBA uncertainty outputs alongside the impact uncertainty outputs

All new outputs are written to `outputs/rome/tables/uncertainty_improved_fast/` so the original `NB09` outputs remain unchanged.

In [1]:
import os
import sys
from pathlib import Path

os.environ.setdefault('CITY', 'rome')
os.environ.setdefault('NB09_N', '512')
os.environ.setdefault('NB09_SEED', '42')
os.environ.setdefault('NB09_MAKE_FIGURES', '0')
os.environ.setdefault('HAZARD_TRACK', 'standard')

def _find_repo_root():
    env = os.environ.get("URBAN_HEAT_ROOT")
    if env:
        root = Path(env).expanduser().resolve()
        if (root / "cityheat").is_dir() and (root / "configs").is_dir():
            return root
    start = Path.cwd().resolve()
    for cand in [start, *start.parents]:
        if (cand / "cityheat").is_dir() and (cand / "configs").is_dir():
            return cand
    raise RuntimeError(
        "Could not locate repo root. Run the notebook from inside the repo "
        "or set URBAN_HEAT_ROOT."
    )

ROOT = _find_repo_root()
os.environ.setdefault('MPLCONFIGDIR', str(ROOT / 'outputs' / '.mpl'))
os.environ.setdefault('XDG_CACHE_HOME', str(ROOT / 'outputs' / '.cache'))
Path(os.environ['MPLCONFIGDIR']).mkdir(parents=True, exist_ok=True)
Path(os.environ['XDG_CACHE_HOME']).mkdir(parents=True, exist_ok=True)
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print('ROOT:', ROOT)
print('CITY:', os.environ['CITY'])
print('NB09_N:', os.environ['NB09_N'])
print('NB09_SEED:', os.environ['NB09_SEED'])

ROOT: /Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat
CITY: rome
NB09_N: 512
NB09_SEED: 42

In [2]:
from cityheat.nb09_improved_fast import run_nb09_improved_fast

paths = run_nb09_improved_fast()
paths

[rome] sample 1/512: year=2050 aai=1.302

[rome] sample 2/512: year=2040 aai=0.867

[rome] sample 3/512: year=2040 aai=0.073

[rome] sample 4/512: year=2020 aai=0.730

[rome] sample 5/512: year=2050 aai=1.884

[rome] sample 6/512: year=2040 aai=0.177

[rome] sample 7/512: year=2050 aai=0.814

[rome] sample 8/512: year=2040 aai=0.843

[rome] sample 9/512: year=2050 aai=0.136

[rome] sample 10/512: year=2020 aai=0.126

[rome] sample 11/512: year=2020 aai=0.922

[rome] sample 12/512: year=2020 aai=0.232

[rome] sample 13/512: year=2020 aai=0.102

[rome] sample 14/512: year=2040 aai=0.092

[rome] sample 15/512: year=2020 aai=0.201

[rome] sample 16/512: year=2050 aai=0.277

[rome] sample 17/512: year=2020 aai=0.106

[rome] sample 18/512: year=2040 aai=0.246

[rome] sample 19/512: year=2050 aai=1.085

[rome] sample 20/512: year=2030 aai=0.908

[rome] sample 21/512: year=2020 aai=0.034

[rome] sample 22/512: year=2030 aai=0.385

[rome] sample 23/512: year=2030 aai=0.018

[rome] sample 24/512: year=2050 aai=0.130

[rome] sample 25/512: year=2040 aai=0.037

[rome] sample 26/512: year=2030 aai=2.336

[rome] sample 27/512: year=2050 aai=0.918

[rome] sample 28/512: year=2040 aai=0.131

[rome] sample 29/512: year=2030 aai=0.043

[rome] sample 30/512: year=2020 aai=0.023

[rome] sample 31/512: year=2020 aai=0.313

[rome] sample 32/512: year=2030 aai=1.094

[rome] sample 33/512: year=2040 aai=0.193

[rome] sample 34/512: year=2030 aai=0.613

[rome] sample 35/512: year=2050 aai=0.072

[rome] sample 36/512: year=2030 aai=0.312

[rome] sample 37/512: year=2040 aai=0.964

[rome] sample 38/512: year=2030 aai=0.903

[rome] sample 39/512: year=2050 aai=0.774

[rome] sample 40/512: year=2020 aai=0.017

[rome] sample 41/512: year=2020 aai=1.343

[rome] sample 42/512: year=2040 aai=0.096

[rome] sample 43/512: year=2020 aai=0.113

[rome] sample 44/512: year=2030 aai=0.110

[rome] sample 45/512: year=2050 aai=0.091

[rome] sample 46/512: year=2020 aai=0.278

[rome] sample 47/512: year=2050 aai=1.823

[rome] sample 48/512: year=2020 aai=0.042

[rome] sample 49/512: year=2050 aai=0.493

[rome] sample 50/512: year=2040 aai=0.193

[rome] sample 51/512: year=2050 aai=0.054

[rome] sample 52/512: year=2020 aai=0.107

[rome] sample 53/512: year=2040 aai=0.259

[rome] sample 54/512: year=2050 aai=0.294

[rome] sample 55/512: year=2020 aai=0.032

[rome] sample 56/512: year=2050 aai=0.724

[rome] sample 57/512: year=2040 aai=0.593

[rome] sample 58/512: year=2040 aai=0.377

[rome] sample 59/512: year=2050 aai=0.066

[rome] sample 60/512: year=2020 aai=0.896

[rome] sample 61/512: year=2050 aai=1.418

[rome] sample 62/512: year=2020 aai=0.002

[rome] sample 63/512: year=2050 aai=1.905

[rome] sample 64/512: year=2020 aai=0.491

[rome] sample 65/512: year=2030 aai=0.419

[rome] sample 66/512: year=2040 aai=0.005

[rome] sample 67/512: year=2020 aai=0.823

[rome] sample 68/512: year=2050 aai=0.054

[rome] sample 69/512: year=2030 aai=0.156

[rome] sample 70/512: year=2020 aai=0.021

[rome] sample 71/512: year=2050 aai=0.211

[rome] sample 72/512: year=2040 aai=0.810

[rome] sample 73/512: year=2040 aai=0.284

[rome] sample 74/512: year=2040 aai=0.611

[rome] sample 75/512: year=2040 aai=0.385

[rome] sample 76/512: year=2040 aai=2.294

[rome] sample 77/512: year=2020 aai=0.078

[rome] sample 78/512: year=2050 aai=0.571

[rome] sample 79/512: year=2050 aai=0.651

[rome] sample 80/512: year=2050 aai=0.374

[rome] sample 81/512: year=2040 aai=0.141

[rome] sample 82/512: year=2020 aai=0.631

[rome] sample 83/512: year=2050 aai=0.149

[rome] sample 84/512: year=2020 aai=1.127

[rome] sample 85/512: year=2040 aai=0.391

[rome] sample 86/512: year=2030 aai=0.035

[rome] sample 87/512: year=2030 aai=1.354

[rome] sample 88/512: year=2030 aai=0.106

[rome] sample 89/512: year=2030 aai=0.050

[rome] sample 90/512: year=2030 aai=0.004

[rome] sample 91/512: year=2030 aai=1.061

[rome] sample 92/512: year=2040 aai=0.144

[rome] sample 93/512: year=2040 aai=0.620

[rome] sample 94/512: year=2030 aai=0.585

[rome] sample 95/512: year=2020 aai=0.561

[rome] sample 96/512: year=2040 aai=0.450

[rome] sample 97/512: year=2020 aai=1.081

[rome] sample 98/512: year=2050 aai=1.510

[rome] sample 99/512: year=2040 aai=0.168

[rome] sample 100/512: year=2030 aai=0.061

[rome] sample 101/512: year=2020 aai=0.024

[rome] sample 102/512: year=2030 aai=0.745

[rome] sample 103/512: year=2020 aai=0.039

[rome] sample 104/512: year=2050 aai=1.704

[rome] sample 105/512: year=2050 aai=0.269

[rome] sample 106/512: year=2050 aai=1.349

[rome] sample 107/512: year=2040 aai=3.234

[rome] sample 108/512: year=2030 aai=0.912

[rome] sample 109/512: year=2020 aai=0.127

[rome] sample 110/512: year=2040 aai=0.541

[rome] sample 111/512: year=2040 aai=0.200

[rome] sample 112/512: year=2040 aai=0.042

[rome] sample 113/512: year=2050 aai=0.155

[rome] sample 114/512: year=2030 aai=0.028

[rome] sample 115/512: year=2030 aai=0.287

[rome] sample 116/512: year=2050 aai=0.235

[rome] sample 117/512: year=2020 aai=0.024

[rome] sample 118/512: year=2050 aai=0.254

[rome] sample 119/512: year=2050 aai=1.480

[rome] sample 120/512: year=2020 aai=0.262

[rome] sample 121/512: year=2030 aai=0.111

[rome] sample 122/512: year=2050 aai=0.081

[rome] sample 123/512: year=2040 aai=2.242

[rome] sample 124/512: year=2040 aai=0.301

[rome] sample 125/512: year=2040 aai=0.177

[rome] sample 126/512: year=2050 aai=0.440

[rome] sample 127/512: year=2020 aai=0.022

[rome] sample 128/512: year=2050 aai=0.921

[rome] sample 129/512: year=2030 aai=2.668

[rome] sample 130/512: year=2040 aai=0.004

[rome] sample 131/512: year=2040 aai=0.492

[rome] sample 132/512: year=2020 aai=0.588

[rome] sample 133/512: year=2050 aai=0.337

[rome] sample 134/512: year=2030 aai=0.020

[rome] sample 135/512: year=2040 aai=0.148

[rome] sample 136/512: year=2030 aai=0.095

[rome] sample 137/512: year=2050 aai=0.008

[rome] sample 138/512: year=2030 aai=0.039

[rome] sample 139/512: year=2040 aai=0.341

[rome] sample 140/512: year=2030 aai=0.046

[rome] sample 141/512: year=2050 aai=0.068

[rome] sample 142/512: year=2030 aai=1.558

[rome] sample 143/512: year=2030 aai=0.295

[rome] sample 144/512: year=2030 aai=0.324

[rome] sample 145/512: year=2040 aai=0.263

[rome] sample 146/512: year=2030 aai=1.586

[rome] sample 147/512: year=2050 aai=0.547

[rome] sample 148/512: year=2030 aai=0.437

[rome] sample 149/512: year=2030 aai=0.414

[rome] sample 150/512: year=2050 aai=0.547

[rome] sample 151/512: year=2050 aai=0.061

[rome] sample 152/512: year=2030 aai=0.531

[rome] sample 153/512: year=2020 aai=0.229

[rome] sample 154/512: year=2040 aai=0.304

[rome] sample 155/512: year=2040 aai=0.512

[rome] sample 156/512: year=2020 aai=1.036

[rome] sample 157/512: year=2040 aai=0.309

[rome] sample 158/512: year=2040 aai=0.042

[rome] sample 159/512: year=2050 aai=1.706

[rome] sample 160/512: year=2030 aai=0.125

[rome] sample 161/512: year=2020 aai=0.089

[rome] sample 162/512: year=2020 aai=0.256

[rome] sample 163/512: year=2040 aai=0.110

[rome] sample 164/512: year=2050 aai=0.504

[rome] sample 165/512: year=2040 aai=0.159

[rome] sample 166/512: year=2050 aai=1.047

[rome] sample 167/512: year=2050 aai=0.009

[rome] sample 168/512: year=2040 aai=1.052

[rome] sample 169/512: year=2020 aai=0.259

[rome] sample 170/512: year=2040 aai=0.542

[rome] sample 171/512: year=2030 aai=0.672

[rome] sample 172/512: year=2050 aai=0.981

[rome] sample 173/512: year=2040 aai=0.230

[rome] sample 174/512: year=2030 aai=0.454

[rome] sample 175/512: year=2040 aai=0.006

[rome] sample 176/512: year=2050 aai=0.809

[rome] sample 177/512: year=2050 aai=1.277

[rome] sample 178/512: year=2040 aai=0.707

[rome] sample 179/512: year=2020 aai=0.110

[rome] sample 180/512: year=2050 aai=0.341

[rome] sample 181/512: year=2040 aai=0.081

[rome] sample 182/512: year=2050 aai=0.253

[rome] sample 183/512: year=2040 aai=0.157

[rome] sample 184/512: year=2050 aai=0.900

[rome] sample 185/512: year=2030 aai=0.341

[rome] sample 186/512: year=2040 aai=1.017

[rome] sample 187/512: year=2030 aai=0.054

[rome] sample 188/512: year=2020 aai=0.018

[rome] sample 189/512: year=2050 aai=0.317

[rome] sample 190/512: year=2020 aai=0.113

[rome] sample 191/512: year=2040 aai=0.885

[rome] sample 192/512: year=2030 aai=0.754

[rome] sample 193/512: year=2050 aai=0.087

[rome] sample 194/512: year=2030 aai=0.085

[rome] sample 195/512: year=2020 aai=0.237

[rome] sample 196/512: year=2030 aai=0.003

[rome] sample 197/512: year=2050 aai=0.693

[rome] sample 198/512: year=2050 aai=0.113

[rome] sample 199/512: year=2040 aai=3.396

[rome] sample 200/512: year=2040 aai=1.550

[rome] sample 201/512: year=2050 aai=0.263

[rome] sample 202/512: year=2020 aai=1.737

[rome] sample 203/512: year=2020 aai=0.246

[rome] sample 204/512: year=2050 aai=0.604

[rome] sample 205/512: year=2040 aai=1.272

[rome] sample 206/512: year=2040 aai=0.421

[rome] sample 207/512: year=2020 aai=0.045

[rome] sample 208/512: year=2020 aai=0.031

[rome] sample 209/512: year=2040 aai=1.347

[rome] sample 210/512: year=2020 aai=0.465

[rome] sample 211/512: year=2020 aai=0.028

[rome] sample 212/512: year=2040 aai=0.178

[rome] sample 213/512: year=2020 aai=0.403

[rome] sample 214/512: year=2040 aai=0.202

[rome] sample 215/512: year=2040 aai=0.631

[rome] sample 216/512: year=2050 aai=0.059

[rome] sample 217/512: year=2030 aai=0.042

[rome] sample 218/512: year=2050 aai=0.350

[rome] sample 219/512: year=2050 aai=0.077

[rome] sample 220/512: year=2030 aai=0.494

[rome] sample 221/512: year=2040 aai=0.043

[rome] sample 222/512: year=2020 aai=0.001

[rome] sample 223/512: year=2020 aai=0.844

[rome] sample 224/512: year=2040 aai=0.448

[rome] sample 225/512: year=2030 aai=0.046

[rome] sample 226/512: year=2040 aai=0.358

[rome] sample 227/512: year=2020 aai=0.321

[rome] sample 228/512: year=2030 aai=0.541

[rome] sample 229/512: year=2050 aai=0.448

[rome] sample 230/512: year=2030 aai=0.791

[rome] sample 231/512: year=2050 aai=1.203

[rome] sample 232/512: year=2040 aai=0.368

[rome] sample 233/512: year=2020 aai=0.391

[rome] sample 234/512: year=2020 aai=0.074

[rome] sample 235/512: year=2040 aai=0.332

[rome] sample 236/512: year=2020 aai=1.519

[rome] sample 237/512: year=2030 aai=0.003

[rome] sample 238/512: year=2040 aai=0.320

[rome] sample 239/512: year=2020 aai=0.244

[rome] sample 240/512: year=2050 aai=0.084

[rome] sample 241/512: year=2040 aai=0.002

[rome] sample 242/512: year=2020 aai=1.201

[rome] sample 243/512: year=2050 aai=0.081

[rome] sample 244/512: year=2040 aai=0.003

[rome] sample 245/512: year=2040 aai=0.071

[rome] sample 246/512: year=2020 aai=2.359

[rome] sample 247/512: year=2020 aai=0.626

[rome] sample 248/512: year=2040 aai=1.537

[rome] sample 249/512: year=2020 aai=1.508

[rome] sample 250/512: year=2030 aai=1.687

[rome] sample 251/512: year=2040 aai=0.325

[rome] sample 252/512: year=2030 aai=0.850

[rome] sample 253/512: year=2050 aai=1.701

[rome] sample 254/512: year=2040 aai=0.062

[rome] sample 255/512: year=2030 aai=0.082

[rome] sample 256/512: year=2050 aai=2.843

[rome] sample 257/512: year=2020 aai=0.152

[rome] sample 258/512: year=2030 aai=0.221

[rome] sample 259/512: year=2020 aai=0.756

[rome] sample 260/512: year=2040 aai=2.050

[rome] sample 261/512: year=2020 aai=0.576

[rome] sample 262/512: year=2050 aai=1.245

[rome] sample 263/512: year=2030 aai=0.369

[rome] sample 264/512: year=2020 aai=0.124

[rome] sample 265/512: year=2050 aai=0.045

[rome] sample 266/512: year=2020 aai=0.189

[rome] sample 267/512: year=2040 aai=0.235

[rome] sample 268/512: year=2040 aai=0.179

[rome] sample 269/512: year=2030 aai=0.558

[rome] sample 270/512: year=2050 aai=0.006

[rome] sample 271/512: year=2030 aai=0.191

[rome] sample 272/512: year=2050 aai=0.911

[rome] sample 273/512: year=2030 aai=0.240

[rome] sample 274/512: year=2040 aai=0.026

[rome] sample 275/512: year=2050 aai=0.293

[rome] sample 276/512: year=2020 aai=0.428

[rome] sample 277/512: year=2020 aai=1.018

[rome] sample 278/512: year=2040 aai=0.421

[rome] sample 279/512: year=2020 aai=0.214

[rome] sample 280/512: year=2030 aai=0.050

[rome] sample 281/512: year=2020 aai=0.072

[rome] sample 282/512: year=2020 aai=0.329

[rome] sample 283/512: year=2040 aai=0.466

[rome] sample 284/512: year=2040 aai=0.243

[rome] sample 285/512: year=2030 aai=0.319

[rome] sample 286/512: year=2040 aai=0.867

[rome] sample 287/512: year=2050 aai=0.119

[rome] sample 288/512: year=2020 aai=1.064

[rome] sample 289/512: year=2030 aai=0.027

[rome] sample 290/512: year=2050 aai=0.672

[rome] sample 291/512: year=2020 aai=0.127

[rome] sample 292/512: year=2040 aai=0.377

[rome] sample 293/512: year=2050 aai=1.683

[rome] sample 294/512: year=2020 aai=0.106

[rome] sample 295/512: year=2030 aai=0.297

[rome] sample 296/512: year=2050 aai=2.428

[rome] sample 297/512: year=2050 aai=0.069

[rome] sample 298/512: year=2050 aai=0.043

[rome] sample 299/512: year=2020 aai=1.333

[rome] sample 300/512: year=2050 aai=0.394

[rome] sample 301/512: year=2030 aai=0.199

[rome] sample 302/512: year=2050 aai=2.584

[rome] sample 303/512: year=2040 aai=0.676

[rome] sample 304/512: year=2040 aai=0.646

[rome] sample 305/512: year=2050 aai=0.351

[rome] sample 306/512: year=2030 aai=1.041

[rome] sample 307/512: year=2030 aai=0.497

[rome] sample 308/512: year=2020 aai=1.288

[rome] sample 309/512: year=2030 aai=0.668

[rome] sample 310/512: year=2050 aai=0.391

[rome] sample 311/512: year=2040 aai=0.158

[rome] sample 312/512: year=2030 aai=0.971

[rome] sample 313/512: year=2020 aai=0.393

[rome] sample 314/512: year=2050 aai=1.885

[rome] sample 315/512: year=2020 aai=0.616

[rome] sample 316/512: year=2050 aai=0.011

[rome] sample 317/512: year=2040 aai=0.282

[rome] sample 318/512: year=2040 aai=0.882

[rome] sample 319/512: year=2050 aai=0.591

[rome] sample 320/512: year=2020 aai=0.595

[rome] sample 321/512: year=2030 aai=0.503

[rome] sample 322/512: year=2050 aai=1.749

[rome] sample 323/512: year=2020 aai=0.074

[rome] sample 324/512: year=2040 aai=0.298

[rome] sample 325/512: year=2030 aai=0.135

[rome] sample 326/512: year=2050 aai=1.103

[rome] sample 327/512: year=2030 aai=0.002

[rome] sample 328/512: year=2020 aai=0.126

[rome] sample 329/512: year=2030 aai=1.736

[rome] sample 330/512: year=2030 aai=0.552

[rome] sample 331/512: year=2030 aai=0.005

[rome] sample 332/512: year=2030 aai=0.433

[rome] sample 333/512: year=2030 aai=2.008

[rome] sample 334/512: year=2040 aai=0.435

[rome] sample 335/512: year=2020 aai=0.284

[rome] sample 336/512: year=2050 aai=0.728

[rome] sample 337/512: year=2020 aai=0.020

[rome] sample 338/512: year=2040 aai=0.520

[rome] sample 339/512: year=2050 aai=0.846

[rome] sample 340/512: year=2050 aai=1.315

[rome] sample 341/512: year=2020 aai=1.668

[rome] sample 342/512: year=2050 aai=0.042

[rome] sample 343/512: year=2040 aai=0.570

[rome] sample 344/512: year=2020 aai=0.621

[rome] sample 345/512: year=2030 aai=0.914

[rome] sample 346/512: year=2030 aai=0.564

[rome] sample 347/512: year=2030 aai=0.014

[rome] sample 348/512: year=2030 aai=0.194

[rome] sample 349/512: year=2030 aai=0.647

[rome] sample 350/512: year=2030 aai=2.251

[rome] sample 351/512: year=2050 aai=2.373

[rome] sample 352/512: year=2020 aai=0.223

[rome] sample 353/512: year=2040 aai=0.166

[rome] sample 354/512: year=2040 aai=0.053

[rome] sample 355/512: year=2020 aai=2.437

[rome] sample 356/512: year=2040 aai=2.667

[rome] sample 357/512: year=2050 aai=0.252

[rome] sample 358/512: year=2020 aai=0.381

[rome] sample 359/512: year=2020 aai=0.300

[rome] sample 360/512: year=2040 aai=2.641

[rome] sample 361/512: year=2040 aai=0.114

[rome] sample 362/512: year=2020 aai=0.393

[rome] sample 363/512: year=2030 aai=0.923

[rome] sample 364/512: year=2020 aai=0.096

[rome] sample 365/512: year=2020 aai=0.031

[rome] sample 366/512: year=2030 aai=0.753

[rome] sample 367/512: year=2020 aai=0.545

[rome] sample 368/512: year=2030 aai=0.457

[rome] sample 369/512: year=2050 aai=0.219

[rome] sample 370/512: year=2030 aai=1.315

[rome] sample 371/512: year=2030 aai=0.003

[rome] sample 372/512: year=2050 aai=0.364

[rome] sample 373/512: year=2040 aai=1.770

[rome] sample 374/512: year=2030 aai=0.072

[rome] sample 375/512: year=2030 aai=0.415

[rome] sample 376/512: year=2030 aai=0.822

[rome] sample 377/512: year=2030 aai=0.143

[rome] sample 378/512: year=2040 aai=0.009

[rome] sample 379/512: year=2020 aai=0.042

[rome] sample 380/512: year=2040 aai=0.037

[rome] sample 381/512: year=2030 aai=0.009

[rome] sample 382/512: year=2030 aai=0.160

[rome] sample 383/512: year=2030 aai=0.413

[rome] sample 384/512: year=2040 aai=1.217

[rome] sample 385/512: year=2030 aai=0.381

[rome] sample 386/512: year=2050 aai=0.242

[rome] sample 387/512: year=2040 aai=0.106

[rome] sample 388/512: year=2050 aai=0.164

[rome] sample 389/512: year=2050 aai=1.680

[rome] sample 390/512: year=2050 aai=0.012

[rome] sample 391/512: year=2020 aai=0.444

[rome] sample 392/512: year=2020 aai=1.217

[rome] sample 393/512: year=2040 aai=1.606

[rome] sample 394/512: year=2040 aai=0.237

[rome] sample 395/512: year=2040 aai=0.112

[rome] sample 396/512: year=2050 aai=0.012

[rome] sample 397/512: year=2020 aai=0.137

[rome] sample 398/512: year=2030 aai=0.030

[rome] sample 399/512: year=2040 aai=0.006

[rome] sample 400/512: year=2020 aai=1.418

[rome] sample 401/512: year=2050 aai=1.166

[rome] sample 402/512: year=2020 aai=0.083

[rome] sample 403/512: year=2030 aai=0.291

[rome] sample 404/512: year=2040 aai=0.033

[rome] sample 405/512: year=2030 aai=0.885

[rome] sample 406/512: year=2050 aai=2.447

[rome] sample 407/512: year=2030 aai=1.980

[rome] sample 408/512: year=2040 aai=0.617

[rome] sample 409/512: year=2050 aai=0.085

[rome] sample 410/512: year=2040 aai=1.732

[rome] sample 411/512: year=2020 aai=0.184

[rome] sample 412/512: year=2030 aai=0.053

[rome] sample 413/512: year=2020 aai=0.053

[rome] sample 414/512: year=2040 aai=0.847

[rome] sample 415/512: year=2050 aai=0.096

[rome] sample 416/512: year=2030 aai=0.037

[rome] sample 417/512: year=2040 aai=0.040

[rome] sample 418/512: year=2050 aai=0.146

[rome] sample 419/512: year=2020 aai=0.001

[rome] sample 420/512: year=2030 aai=0.771

[rome] sample 421/512: year=2050 aai=0.339

[rome] sample 422/512: year=2040 aai=0.254

[rome] sample 423/512: year=2030 aai=0.006

[rome] sample 424/512: year=2030 aai=0.734

[rome] sample 425/512: year=2020 aai=0.041

[rome] sample 426/512: year=2020 aai=0.148

[rome] sample 427/512: year=2040 aai=1.548

[rome] sample 428/512: year=2050 aai=0.037

[rome] sample 429/512: year=2050 aai=0.196

[rome] sample 430/512: year=2050 aai=0.756

[rome] sample 431/512: year=2020 aai=0.015

[rome] sample 432/512: year=2030 aai=0.058

[rome] sample 433/512: year=2030 aai=0.927

[rome] sample 434/512: year=2020 aai=0.050

[rome] sample 435/512: year=2050 aai=0.004

[rome] sample 436/512: year=2050 aai=0.452

[rome] sample 437/512: year=2020 aai=0.421

[rome] sample 438/512: year=2050 aai=0.110

[rome] sample 439/512: year=2030 aai=1.525

[rome] sample 440/512: year=2020 aai=2.397

[rome] sample 441/512: year=2030 aai=0.022

[rome] sample 442/512: year=2050 aai=0.167

[rome] sample 443/512: year=2030 aai=0.122

[rome] sample 444/512: year=2050 aai=1.304

[rome] sample 445/512: year=2030 aai=0.030

[rome] sample 446/512: year=2030 aai=0.294

[rome] sample 447/512: year=2050 aai=0.427

[rome] sample 448/512: year=2030 aai=0.461

[rome] sample 449/512: year=2050 aai=0.038

[rome] sample 450/512: year=2020 aai=0.662

[rome] sample 451/512: year=2030 aai=0.654

[rome] sample 452/512: year=2040 aai=0.043

[rome] sample 453/512: year=2040 aai=0.918

[rome] sample 454/512: year=2020 aai=1.055

[rome] sample 455/512: year=2050 aai=0.447

[rome] sample 456/512: year=2050 aai=1.402

[rome] sample 457/512: year=2040 aai=0.139

[rome] sample 458/512: year=2020 aai=0.042

[rome] sample 459/512: year=2040 aai=0.169

[rome] sample 460/512: year=2020 aai=0.089

[rome] sample 461/512: year=2020 aai=0.064

[rome] sample 462/512: year=2050 aai=1.437

[rome] sample 463/512: year=2020 aai=0.080

[rome] sample 464/512: year=2020 aai=0.205

[rome] sample 465/512: year=2050 aai=0.137

[rome] sample 466/512: year=2030 aai=0.050

[rome] sample 467/512: year=2030 aai=1.305

[rome] sample 468/512: year=2020 aai=0.077

[rome] sample 469/512: year=2050 aai=1.513

[rome] sample 470/512: year=2030 aai=0.209

[rome] sample 471/512: year=2040 aai=0.187

[rome] sample 472/512: year=2030 aai=1.154

[rome] sample 473/512: year=2020 aai=0.055

[rome] sample 474/512: year=2030 aai=1.159

[rome] sample 475/512: year=2050 aai=1.238

[rome] sample 476/512: year=2040 aai=0.206

[rome] sample 477/512: year=2040 aai=0.199

[rome] sample 478/512: year=2040 aai=1.491

[rome] sample 479/512: year=2030 aai=0.185

[rome] sample 480/512: year=2020 aai=0.036

[rome] sample 481/512: year=2050 aai=0.613

[rome] sample 482/512: year=2050 aai=1.379

[rome] sample 483/512: year=2020 aai=0.957

[rome] sample 484/512: year=2020 aai=0.413

[rome] sample 485/512: year=2030 aai=0.281

[rome] sample 486/512: year=2040 aai=0.230

[rome] sample 487/512: year=2020 aai=0.156

[rome] sample 488/512: year=2040 aai=0.225

[rome] sample 489/512: year=2040 aai=1.256

[rome] sample 490/512: year=2030 aai=0.168

[rome] sample 491/512: year=2020 aai=1.381

[rome] sample 492/512: year=2030 aai=0.039

[rome] sample 493/512: year=2020 aai=0.030

[rome] sample 494/512: year=2050 aai=0.684

[rome] sample 495/512: year=2020 aai=0.265

[rome] sample 496/512: year=2050 aai=0.738

[rome] sample 497/512: year=2040 aai=3.171

[rome] sample 498/512: year=2030 aai=0.092

[rome] sample 499/512: year=2030 aai=0.041

[rome] sample 500/512: year=2040 aai=0.622

[rome] sample 501/512: year=2030 aai=0.104

[rome] sample 502/512: year=2040 aai=0.225

[rome] sample 503/512: year=2040 aai=0.255

[rome] sample 504/512: year=2050 aai=0.215

[rome] sample 505/512: year=2020 aai=0.927

[rome] sample 506/512: year=2030 aai=0.744

[rome] sample 507/512: year=2030 aai=0.763

[rome] sample 508/512: year=2020 aai=0.592

[rome] sample 509/512: year=2020 aai=2.005

[rome] sample 510/512: year=2050 aai=0.045

[rome] sample 511/512: year=2030 aai=1.235

[rome] sample 512/512: year=2020 aai=0.042

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))
/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))
/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

{'samples': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_samples_rome_improved.csv'),
 'impact': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_impact_summary_rome_improved.csv'),
 'freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_freq_curve_rome_improved.csv'),
 'cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_cba_ews_rome_improved.csv'),
 'cba_ac': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_cba_ac_rome_improved.csv'),
 'cba_trees': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_cba_trees_rome_improved.csv'),
 'vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_vulnerability_rome_improved.csv'),
 'sens_aai': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_aai_agg_rome_improved.csv'),
 'sens_freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_freq_curve_rome_improved.csv'),
 'sens_cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_cba_ews_rome_improved.csv'),
 'sens_cba_ac': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_cba_ac_rome_improved.csv'),
 'sens_cba_trees': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_cba_trees_rome_improved.csv'),
 'sens_vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/sens_vulnerability_rome_improved.csv'),
 'meta': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/uq_dimensions_rome_improved.json'),
 'bundle': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_impact_rome_march2026_improved.h5'),
 'bundle_sens': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/rome/tables/uncertainty_improved/unc_impact_rome_march2026_improved_with_sensitivity.h5')}

In [3]:
import pandas as pd

samples = pd.read_csv(paths['samples'])
samples[[
    'year', 'aai_agg', 'annual_deaths', 'sample_warning_days',
    'sample_threshold_deaths_per_day', 'ews_pv_cost_25y',
    'ews_net_avoided_deaths_25y_cum', 'ews_cost_per_net_death_25y_cum'
]].head(10)

,year,aai_agg,annual_deaths,sample_warning_days,sample_threshold_deaths_per_day,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_cost_per_net_death_25y_cum
0,2050,1.302456,475.396449,55.0,3.637959,2.542400e+06,348.845313,7288.043846
1,2040,0.866615,317.181143,36.0,3.727239,1.466499e+07,589.603098,24872.655583
2,2040,0.072978,26.710057,27.0,0.361295,1.508357e+06,46.308665,32571.807038
3,2020,0.730367,267.314385,23.0,3.462437,3.717191e+06,1510.457293,2460.970556
4,2050,1.884399,687.805513,18.0,8.242110,1.155843e+06,251.107020,4602.991453
5,2040,0.176946,64.762360,45.0,1.002148,3.314603e+06,330.123314,10040.499510
6,2050,0.813701,297.000717,50.0,2.416990,1.315890e+07,293.620975,44815.948506
7,2040,0.842997,308.536902,39.0,3.273643,1.604240e+07,1117.839944,14351.250534
8,2050,0.136003,49.641008,56.0,0.305889,2.883873e+06,37.342750,77227.111709
9,2020,0.125858,46.064151,30.0,0.606324,4.191091e+06,41.725216,100445.037688

In [4]:
impact_summary = pd.read_csv(paths['impact'])
cba_summary = pd.read_csv(paths['cba'])

display(impact_summary.describe())
display(cba_summary.describe())

,aai_agg,annual_deaths,rp2,rp5,rp10,rp20
count,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000
mean,0.551031,201.382601,0.005078,0.965387,2.000073,2.784598
std,0.623436,227.855508,0.025819,1.394280,2.221192,2.873068
min,0.001271,0.465338,0.000000,0.000000,0.000022,0.000880
25%,0.096401,35.282815,0.000000,0.019662,0.306690,0.605572
50%,0.310373,113.440804,0.000000,0.384307,1.232013,1.686112
75%,0.795509,290.360656,0.000000,1.439236,3.002513,4.100906
max,3.396384,1243.076498,0.402590,7.903213,11.629321,14.712221

,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_net_avoided_deaths_25y_pv,ews_cost_per_net_death_25y_cum,ews_cost_per_net_death_25y_pv,ews_life_years_saved_25y_cum
count,5.120000e+02,512.000000,512.000000,5.120000e+02,5.120000e+02,512.000000
mean,9.861494e+06,321.818232,203.692400,3.700032e+05,5.698323e+05,4206.111336
std,8.088034e+06,412.619193,266.015240,1.529134e+06,2.324749e+06,5471.468810
min,1.090120e+06,0.750818,0.423593,1.210655e+03,2.386020e+03,9.596827
25%,2.979196e+06,56.046147,34.668707,1.284036e+04,1.921622e+04,717.566737
50%,5.859088e+06,161.583886,108.211543,3.974948e+04,6.621050e+04,2075.605525
75%,1.610711e+07,393.850710,251.158206,1.432609e+05,2.363524e+05,5277.400836
max,3.185361e+07,2393.921878,1798.893306,2.245313e+07,3.531559e+07,30610.184896