# Notebook 09 - Uncertainty Quantification (Second version)

City-agnostic improved workflow for **Lisbon**. This version keeps the
original March 2026 `NB09` untouched and adds three targeted
improvements: 
- spatially explicit daily raster modifiers for trees and
waste heat
- event-level warning-day logic for EWS
- - EWS CBA uncertainty
outputs alongside the impact uncertainty outputs

All new outputs are written to
`outputs/lisbon/tables/uncertainty_improved/` so the original `NB09`
outputs remain unchanged.

In [1]:
import os
import sys
from pathlib import Path

os.environ.setdefault('CITY', 'lisbon')
os.environ.setdefault('NB09_N', '512')
os.environ.setdefault('NB09_SEED', '42')

def _find_repo_root():
    env = os.environ.get("URBAN_HEAT_ROOT")
    if env:
        root = Path(env).expanduser().resolve()
        if (root / "cityheat").is_dir() and (root / "configs").is_dir():
            return root
    start = Path.cwd().resolve()
    for cand in [start, *start.parents]:
        if (cand / "cityheat").is_dir() and (cand / "configs").is_dir():
            return cand
    raise RuntimeError(
        "Could not locate repo root. Run the notebook from inside the repo "
        "or set URBAN_HEAT_ROOT."
    )

ROOT = _find_repo_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print('ROOT:', ROOT)
print('CITY:', os.environ['CITY'])
print('NB09_N:', os.environ['NB09_N'])
print('NB09_SEED:', os.environ['NB09_SEED'])

ROOT: /Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat
CITY: lisbon
NB09_N: 512
NB09_SEED: 42

In [2]:
from cityheat.nb09_improved import run_nb09_improved

paths = run_nb09_improved()
paths

Matplotlib is building the font cache; this may take a moment.

[lisbon] sample 1/512: year=2050 aai=0.520

[lisbon] sample 2/512: year=2030 aai=0.093

[lisbon] sample 3/512: year=2040 aai=0.318

[lisbon] sample 4/512: year=2020 aai=0.003

[lisbon] sample 5/512: year=2020 aai=0.457

[lisbon] sample 6/512: year=2030 aai=0.124

[lisbon] sample 7/512: year=2040 aai=0.031

[lisbon] sample 8/512: year=2050 aai=0.009

[lisbon] sample 9/512: year=2020 aai=0.307

[lisbon] sample 10/512: year=2040 aai=0.152

[lisbon] sample 11/512: year=2040 aai=0.030

[lisbon] sample 12/512: year=2020 aai=0.029

[lisbon] sample 13/512: year=2040 aai=0.011

[lisbon] sample 14/512: year=2020 aai=0.186

[lisbon] sample 15/512: year=2040 aai=0.909

[lisbon] sample 16/512: year=2050 aai=0.012

[lisbon] sample 17/512: year=2020 aai=0.474

[lisbon] sample 18/512: year=2050 aai=0.032

[lisbon] sample 19/512: year=2040 aai=0.539

[lisbon] sample 20/512: year=2020 aai=0.075

[lisbon] sample 21/512: year=2020 aai=0.419

[lisbon] sample 22/512: year=2050 aai=0.000

[lisbon] sample 23/512: year=2020 aai=0.180

[lisbon] sample 24/512: year=2030 aai=0.103

[lisbon] sample 25/512: year=2050 aai=0.322

[lisbon] sample 26/512: year=2030 aai=0.118

[lisbon] sample 27/512: year=2020 aai=0.007

[lisbon] sample 28/512: year=2050 aai=0.294

[lisbon] sample 29/512: year=2030 aai=0.190

[lisbon] sample 30/512: year=2030 aai=0.144

[lisbon] sample 31/512: year=2020 aai=0.329

[lisbon] sample 32/512: year=2030 aai=0.067

[lisbon] sample 33/512: year=2020 aai=0.320

[lisbon] sample 34/512: year=2020 aai=0.404

[lisbon] sample 35/512: year=2040 aai=0.018

[lisbon] sample 36/512: year=2040 aai=0.368

[lisbon] sample 37/512: year=2040 aai=0.007

[lisbon] sample 38/512: year=2050 aai=0.577

[lisbon] sample 39/512: year=2040 aai=0.402

[lisbon] sample 40/512: year=2050 aai=0.432

[lisbon] sample 41/512: year=2030 aai=0.023

[lisbon] sample 42/512: year=2020 aai=0.390

[lisbon] sample 43/512: year=2020 aai=0.060

[lisbon] sample 44/512: year=2040 aai=0.127

[lisbon] sample 45/512: year=2050 aai=0.030

[lisbon] sample 46/512: year=2050 aai=0.060

[lisbon] sample 47/512: year=2040 aai=0.193

[lisbon] sample 48/512: year=2040 aai=0.020

[lisbon] sample 49/512: year=2030 aai=0.046

[lisbon] sample 50/512: year=2040 aai=0.260

[lisbon] sample 51/512: year=2020 aai=0.000

[lisbon] sample 52/512: year=2050 aai=0.212

[lisbon] sample 53/512: year=2040 aai=0.891

[lisbon] sample 54/512: year=2020 aai=0.058

[lisbon] sample 55/512: year=2050 aai=0.452

[lisbon] sample 56/512: year=2040 aai=0.149

[lisbon] sample 57/512: year=2030 aai=0.119

[lisbon] sample 58/512: year=2020 aai=0.141

[lisbon] sample 59/512: year=2020 aai=0.125

[lisbon] sample 60/512: year=2040 aai=0.000

[lisbon] sample 61/512: year=2040 aai=0.152

[lisbon] sample 62/512: year=2050 aai=1.045

[lisbon] sample 63/512: year=2050 aai=0.032

[lisbon] sample 64/512: year=2040 aai=0.502

[lisbon] sample 65/512: year=2020 aai=0.052

[lisbon] sample 66/512: year=2030 aai=0.329

[lisbon] sample 67/512: year=2030 aai=0.311

[lisbon] sample 68/512: year=2050 aai=0.023

[lisbon] sample 69/512: year=2020 aai=0.018

[lisbon] sample 70/512: year=2040 aai=0.000

[lisbon] sample 71/512: year=2050 aai=0.274

[lisbon] sample 72/512: year=2030 aai=0.058

[lisbon] sample 73/512: year=2030 aai=0.013

[lisbon] sample 74/512: year=2030 aai=0.380

[lisbon] sample 75/512: year=2020 aai=0.017

[lisbon] sample 76/512: year=2020 aai=0.365

[lisbon] sample 77/512: year=2020 aai=0.000

[lisbon] sample 78/512: year=2050 aai=0.238

[lisbon] sample 79/512: year=2050 aai=0.000

[lisbon] sample 80/512: year=2050 aai=0.047

[lisbon] sample 81/512: year=2020 aai=0.330

[lisbon] sample 82/512: year=2050 aai=0.237

[lisbon] sample 83/512: year=2020 aai=0.036

[lisbon] sample 84/512: year=2020 aai=0.005

[lisbon] sample 85/512: year=2050 aai=0.000

[lisbon] sample 86/512: year=2050 aai=0.292

[lisbon] sample 87/512: year=2050 aai=0.160

[lisbon] sample 88/512: year=2020 aai=0.207

[lisbon] sample 89/512: year=2040 aai=0.579

[lisbon] sample 90/512: year=2040 aai=0.000

[lisbon] sample 91/512: year=2020 aai=0.000

[lisbon] sample 92/512: year=2030 aai=0.000

[lisbon] sample 93/512: year=2030 aai=0.136

[lisbon] sample 94/512: year=2030 aai=0.096

[lisbon] sample 95/512: year=2030 aai=0.001

[lisbon] sample 96/512: year=2020 aai=0.000

[lisbon] sample 97/512: year=2050 aai=0.176

[lisbon] sample 98/512: year=2030 aai=0.000

[lisbon] sample 99/512: year=2040 aai=0.130

[lisbon] sample 100/512: year=2020 aai=0.061

[lisbon] sample 101/512: year=2030 aai=0.000

[lisbon] sample 102/512: year=2040 aai=0.171

[lisbon] sample 103/512: year=2040 aai=0.000

[lisbon] sample 104/512: year=2030 aai=0.074

[lisbon] sample 105/512: year=2030 aai=0.135

[lisbon] sample 106/512: year=2050 aai=0.010

[lisbon] sample 107/512: year=2020 aai=0.038

[lisbon] sample 108/512: year=2040 aai=0.116

[lisbon] sample 109/512: year=2050 aai=0.034

[lisbon] sample 110/512: year=2020 aai=0.091

[lisbon] sample 111/512: year=2040 aai=0.023

[lisbon] sample 112/512: year=2030 aai=0.049

[lisbon] sample 113/512: year=2020 aai=0.117

[lisbon] sample 114/512: year=2030 aai=0.137

[lisbon] sample 115/512: year=2020 aai=0.321

[lisbon] sample 116/512: year=2050 aai=0.208

[lisbon] sample 117/512: year=2030 aai=0.036

[lisbon] sample 118/512: year=2050 aai=0.095

[lisbon] sample 119/512: year=2030 aai=0.463

[lisbon] sample 120/512: year=2020 aai=0.055

[lisbon] sample 121/512: year=2020 aai=0.454

[lisbon] sample 122/512: year=2040 aai=0.876

[lisbon] sample 123/512: year=2030 aai=0.024

[lisbon] sample 124/512: year=2040 aai=0.021

[lisbon] sample 125/512: year=2020 aai=0.294

[lisbon] sample 126/512: year=2020 aai=0.144

[lisbon] sample 127/512: year=2040 aai=0.340

[lisbon] sample 128/512: year=2030 aai=0.005

[lisbon] sample 129/512: year=2030 aai=0.135

[lisbon] sample 130/512: year=2020 aai=0.384

[lisbon] sample 131/512: year=2030 aai=0.007

[lisbon] sample 132/512: year=2050 aai=0.133

[lisbon] sample 133/512: year=2030 aai=0.033

[lisbon] sample 134/512: year=2050 aai=0.028

[lisbon] sample 135/512: year=2040 aai=0.239

[lisbon] sample 136/512: year=2030 aai=0.630

[lisbon] sample 137/512: year=2050 aai=0.924

[lisbon] sample 138/512: year=2020 aai=0.041

[lisbon] sample 139/512: year=2020 aai=0.299

[lisbon] sample 140/512: year=2050 aai=0.007

[lisbon] sample 141/512: year=2030 aai=0.024

[lisbon] sample 142/512: year=2020 aai=0.158

[lisbon] sample 143/512: year=2040 aai=0.005

[lisbon] sample 144/512: year=2050 aai=0.553

[lisbon] sample 145/512: year=2020 aai=0.004

[lisbon] sample 146/512: year=2030 aai=0.008

[lisbon] sample 147/512: year=2050 aai=0.135

[lisbon] sample 148/512: year=2020 aai=0.010

[lisbon] sample 149/512: year=2020 aai=0.051

[lisbon] sample 150/512: year=2030 aai=0.315

[lisbon] sample 151/512: year=2040 aai=0.357

[lisbon] sample 152/512: year=2040 aai=0.585

[lisbon] sample 153/512: year=2030 aai=0.000

[lisbon] sample 154/512: year=2050 aai=0.165

[lisbon] sample 155/512: year=2020 aai=0.013

[lisbon] sample 156/512: year=2020 aai=0.064

[lisbon] sample 157/512: year=2040 aai=0.007

[lisbon] sample 158/512: year=2050 aai=0.058

[lisbon] sample 159/512: year=2050 aai=0.003

[lisbon] sample 160/512: year=2040 aai=0.197

[lisbon] sample 161/512: year=2040 aai=0.139

[lisbon] sample 162/512: year=2050 aai=0.275

[lisbon] sample 163/512: year=2040 aai=0.058

[lisbon] sample 164/512: year=2030 aai=1.073

[lisbon] sample 165/512: year=2030 aai=0.333

[lisbon] sample 166/512: year=2030 aai=0.688

[lisbon] sample 167/512: year=2050 aai=0.056

[lisbon] sample 168/512: year=2040 aai=0.095

[lisbon] sample 169/512: year=2040 aai=0.197

[lisbon] sample 170/512: year=2050 aai=0.011

[lisbon] sample 171/512: year=2020 aai=0.073

[lisbon] sample 172/512: year=2040 aai=0.061

[lisbon] sample 173/512: year=2020 aai=0.140

[lisbon] sample 174/512: year=2030 aai=0.008

[lisbon] sample 175/512: year=2040 aai=0.000

[lisbon] sample 176/512: year=2030 aai=0.112

[lisbon] sample 177/512: year=2040 aai=0.024

[lisbon] sample 178/512: year=2040 aai=0.147

[lisbon] sample 179/512: year=2050 aai=0.006

[lisbon] sample 180/512: year=2050 aai=0.982

[lisbon] sample 181/512: year=2050 aai=0.009

[lisbon] sample 182/512: year=2020 aai=0.023

[lisbon] sample 183/512: year=2040 aai=0.016

[lisbon] sample 184/512: year=2020 aai=0.032

[lisbon] sample 185/512: year=2030 aai=0.011

[lisbon] sample 186/512: year=2040 aai=0.116

[lisbon] sample 187/512: year=2040 aai=1.092

[lisbon] sample 188/512: year=2040 aai=0.017

[lisbon] sample 189/512: year=2030 aai=0.061

[lisbon] sample 190/512: year=2030 aai=0.347

[lisbon] sample 191/512: year=2030 aai=0.058

[lisbon] sample 192/512: year=2040 aai=0.163

[lisbon] sample 193/512: year=2020 aai=0.124

[lisbon] sample 194/512: year=2030 aai=0.154

[lisbon] sample 195/512: year=2020 aai=0.048

[lisbon] sample 196/512: year=2050 aai=0.649

[lisbon] sample 197/512: year=2020 aai=0.718

[lisbon] sample 198/512: year=2020 aai=0.005

[lisbon] sample 199/512: year=2050 aai=0.165

[lisbon] sample 200/512: year=2040 aai=0.005

[lisbon] sample 201/512: year=2050 aai=0.047

[lisbon] sample 202/512: year=2030 aai=0.014

[lisbon] sample 203/512: year=2020 aai=0.000

[lisbon] sample 204/512: year=2050 aai=0.403

[lisbon] sample 205/512: year=2040 aai=0.154

[lisbon] sample 206/512: year=2020 aai=0.132

[lisbon] sample 207/512: year=2040 aai=0.004

[lisbon] sample 208/512: year=2030 aai=0.006

[lisbon] sample 209/512: year=2020 aai=0.000

[lisbon] sample 210/512: year=2030 aai=0.546

[lisbon] sample 211/512: year=2030 aai=0.016

[lisbon] sample 212/512: year=2050 aai=0.000

[lisbon] sample 213/512: year=2040 aai=0.049

[lisbon] sample 214/512: year=2040 aai=0.154

[lisbon] sample 215/512: year=2030 aai=0.005

[lisbon] sample 216/512: year=2030 aai=0.026

[lisbon] sample 217/512: year=2020 aai=0.000

[lisbon] sample 218/512: year=2020 aai=0.129

[lisbon] sample 219/512: year=2020 aai=0.416

[lisbon] sample 220/512: year=2050 aai=0.008

[lisbon] sample 221/512: year=2050 aai=0.108

[lisbon] sample 222/512: year=2040 aai=0.026

[lisbon] sample 223/512: year=2040 aai=0.000

[lisbon] sample 224/512: year=2040 aai=0.016

[lisbon] sample 225/512: year=2050 aai=0.092

[lisbon] sample 226/512: year=2020 aai=0.823

[lisbon] sample 227/512: year=2030 aai=0.003

[lisbon] sample 228/512: year=2030 aai=0.218

[lisbon] sample 229/512: year=2040 aai=0.030

[lisbon] sample 230/512: year=2050 aai=0.005

[lisbon] sample 231/512: year=2030 aai=0.012

[lisbon] sample 232/512: year=2050 aai=0.017

[lisbon] sample 233/512: year=2030 aai=0.792

[lisbon] sample 234/512: year=2020 aai=0.131

[lisbon] sample 235/512: year=2020 aai=0.000

[lisbon] sample 236/512: year=2050 aai=0.004

[lisbon] sample 237/512: year=2050 aai=0.671

[lisbon] sample 238/512: year=2020 aai=0.091

[lisbon] sample 239/512: year=2040 aai=0.363

[lisbon] sample 240/512: year=2050 aai=0.000

[lisbon] sample 241/512: year=2040 aai=0.085

[lisbon] sample 242/512: year=2040 aai=0.020

[lisbon] sample 243/512: year=2030 aai=0.031

[lisbon] sample 244/512: year=2040 aai=0.040

[lisbon] sample 245/512: year=2050 aai=0.026

[lisbon] sample 246/512: year=2050 aai=0.132

[lisbon] sample 247/512: year=2040 aai=0.000

[lisbon] sample 248/512: year=2020 aai=0.488

[lisbon] sample 249/512: year=2030 aai=0.539

[lisbon] sample 250/512: year=2040 aai=0.017

[lisbon] sample 251/512: year=2050 aai=0.000

[lisbon] sample 252/512: year=2030 aai=0.000

[lisbon] sample 253/512: year=2020 aai=0.006

[lisbon] sample 254/512: year=2050 aai=0.006

[lisbon] sample 255/512: year=2040 aai=0.006

[lisbon] sample 256/512: year=2040 aai=0.151

[lisbon] sample 257/512: year=2020 aai=0.035

[lisbon] sample 258/512: year=2020 aai=0.245

[lisbon] sample 259/512: year=2030 aai=0.004

[lisbon] sample 260/512: year=2040 aai=0.012

[lisbon] sample 261/512: year=2020 aai=0.015

[lisbon] sample 262/512: year=2050 aai=0.046

[lisbon] sample 263/512: year=2050 aai=0.161

[lisbon] sample 264/512: year=2020 aai=0.296

[lisbon] sample 265/512: year=2020 aai=0.051

[lisbon] sample 266/512: year=2050 aai=0.057

[lisbon] sample 267/512: year=2030 aai=0.192

[lisbon] sample 268/512: year=2030 aai=0.005

[lisbon] sample 269/512: year=2020 aai=0.013

[lisbon] sample 270/512: year=2040 aai=0.009

[lisbon] sample 271/512: year=2050 aai=0.430

[lisbon] sample 272/512: year=2040 aai=0.168

[lisbon] sample 273/512: year=2040 aai=0.000

[lisbon] sample 274/512: year=2040 aai=0.478

[lisbon] sample 275/512: year=2030 aai=0.025

[lisbon] sample 276/512: year=2030 aai=0.036

[lisbon] sample 277/512: year=2040 aai=0.057

[lisbon] sample 278/512: year=2020 aai=0.055

[lisbon] sample 279/512: year=2020 aai=0.000

[lisbon] sample 280/512: year=2050 aai=0.512

[lisbon] sample 281/512: year=2050 aai=0.349

[lisbon] sample 282/512: year=2030 aai=0.430

[lisbon] sample 283/512: year=2020 aai=0.000

[lisbon] sample 284/512: year=2020 aai=0.004

[lisbon] sample 285/512: year=2040 aai=0.031

[lisbon] sample 286/512: year=2030 aai=0.106

[lisbon] sample 287/512: year=2030 aai=0.345

[lisbon] sample 288/512: year=2030 aai=0.000

[lisbon] sample 289/512: year=2040 aai=0.127

[lisbon] sample 290/512: year=2050 aai=0.001

[lisbon] sample 291/512: year=2040 aai=0.022

[lisbon] sample 292/512: year=2050 aai=0.150

[lisbon] sample 293/512: year=2030 aai=0.004

[lisbon] sample 294/512: year=2050 aai=0.442

[lisbon] sample 295/512: year=2040 aai=0.135

[lisbon] sample 296/512: year=2020 aai=0.002

[lisbon] sample 297/512: year=2050 aai=0.025

[lisbon] sample 298/512: year=2040 aai=0.034

[lisbon] sample 299/512: year=2040 aai=0.052

[lisbon] sample 300/512: year=2020 aai=0.047

[lisbon] sample 301/512: year=2050 aai=0.569

[lisbon] sample 302/512: year=2050 aai=0.000

[lisbon] sample 303/512: year=2040 aai=0.009

[lisbon] sample 304/512: year=2030 aai=0.092

[lisbon] sample 305/512: year=2020 aai=0.053

[lisbon] sample 306/512: year=2030 aai=0.003

[lisbon] sample 307/512: year=2040 aai=0.184

[lisbon] sample 308/512: year=2050 aai=0.126

[lisbon] sample 309/512: year=2030 aai=0.003

[lisbon] sample 310/512: year=2030 aai=0.004

[lisbon] sample 311/512: year=2020 aai=0.090

[lisbon] sample 312/512: year=2020 aai=0.000

[lisbon] sample 313/512: year=2030 aai=0.289

[lisbon] sample 314/512: year=2050 aai=0.005

[lisbon] sample 315/512: year=2020 aai=0.115

[lisbon] sample 316/512: year=2040 aai=0.548

[lisbon] sample 317/512: year=2040 aai=0.021

[lisbon] sample 318/512: year=2040 aai=0.024

[lisbon] sample 319/512: year=2040 aai=0.164

[lisbon] sample 320/512: year=2040 aai=0.140

[lisbon] sample 321/512: year=2050 aai=0.010

[lisbon] sample 322/512: year=2040 aai=0.003

[lisbon] sample 323/512: year=2040 aai=0.019

[lisbon] sample 324/512: year=2040 aai=0.005

[lisbon] sample 325/512: year=2030 aai=0.384

[lisbon] sample 326/512: year=2040 aai=0.000

[lisbon] sample 327/512: year=2030 aai=0.134

[lisbon] sample 328/512: year=2050 aai=0.000

[lisbon] sample 329/512: year=2040 aai=0.010

[lisbon] sample 330/512: year=2040 aai=0.009

[lisbon] sample 331/512: year=2030 aai=0.032

[lisbon] sample 332/512: year=2050 aai=0.008

[lisbon] sample 333/512: year=2030 aai=0.057

[lisbon] sample 334/512: year=2030 aai=0.000

[lisbon] sample 335/512: year=2020 aai=0.019

[lisbon] sample 336/512: year=2040 aai=0.021

[lisbon] sample 337/512: year=2050 aai=0.007

[lisbon] sample 338/512: year=2040 aai=1.246

[lisbon] sample 339/512: year=2040 aai=0.004

[lisbon] sample 340/512: year=2020 aai=0.000

[lisbon] sample 341/512: year=2020 aai=0.016

[lisbon] sample 342/512: year=2030 aai=0.223

[lisbon] sample 343/512: year=2040 aai=0.016

[lisbon] sample 344/512: year=2050 aai=0.005

[lisbon] sample 345/512: year=2020 aai=0.394

[lisbon] sample 346/512: year=2050 aai=0.000

[lisbon] sample 347/512: year=2050 aai=0.224

[lisbon] sample 348/512: year=2030 aai=0.296

[lisbon] sample 349/512: year=2020 aai=0.019

[lisbon] sample 350/512: year=2030 aai=0.191

[lisbon] sample 351/512: year=2030 aai=0.348

[lisbon] sample 352/512: year=2020 aai=0.020

[lisbon] sample 353/512: year=2030 aai=0.056

[lisbon] sample 354/512: year=2050 aai=0.074

[lisbon] sample 355/512: year=2020 aai=0.016

[lisbon] sample 356/512: year=2030 aai=0.004

[lisbon] sample 357/512: year=2050 aai=0.762

[lisbon] sample 358/512: year=2020 aai=0.006

[lisbon] sample 359/512: year=2050 aai=0.014

[lisbon] sample 360/512: year=2030 aai=0.155

[lisbon] sample 361/512: year=2020 aai=0.002

[lisbon] sample 362/512: year=2020 aai=0.049

[lisbon] sample 363/512: year=2030 aai=0.010

[lisbon] sample 364/512: year=2030 aai=0.117

[lisbon] sample 365/512: year=2020 aai=0.128

[lisbon] sample 366/512: year=2040 aai=0.113

[lisbon] sample 367/512: year=2020 aai=0.108

[lisbon] sample 368/512: year=2030 aai=0.038

[lisbon] sample 369/512: year=2030 aai=0.006

[lisbon] sample 370/512: year=2020 aai=0.184

[lisbon] sample 371/512: year=2050 aai=0.000

[lisbon] sample 372/512: year=2050 aai=0.217

[lisbon] sample 373/512: year=2020 aai=0.068

[lisbon] sample 374/512: year=2020 aai=0.017

[lisbon] sample 375/512: year=2030 aai=0.004

[lisbon] sample 376/512: year=2020 aai=0.022

[lisbon] sample 377/512: year=2050 aai=0.003

[lisbon] sample 378/512: year=2020 aai=0.043

[lisbon] sample 379/512: year=2020 aai=0.283

[lisbon] sample 380/512: year=2030 aai=0.125

[lisbon] sample 381/512: year=2040 aai=0.088

[lisbon] sample 382/512: year=2020 aai=0.003

[lisbon] sample 383/512: year=2020 aai=0.007

[lisbon] sample 384/512: year=2050 aai=0.063

[lisbon] sample 385/512: year=2040 aai=0.056

[lisbon] sample 386/512: year=2030 aai=0.051

[lisbon] sample 387/512: year=2050 aai=0.290

[lisbon] sample 388/512: year=2020 aai=0.000

[lisbon] sample 389/512: year=2030 aai=0.042

[lisbon] sample 390/512: year=2040 aai=0.031

[lisbon] sample 391/512: year=2050 aai=0.100

[lisbon] sample 392/512: year=2050 aai=0.017

[lisbon] sample 393/512: year=2020 aai=0.002

[lisbon] sample 394/512: year=2050 aai=0.014

[lisbon] sample 395/512: year=2050 aai=0.117

[lisbon] sample 396/512: year=2020 aai=0.072

[lisbon] sample 397/512: year=2030 aai=0.006

[lisbon] sample 398/512: year=2050 aai=0.627

[lisbon] sample 399/512: year=2030 aai=0.001

[lisbon] sample 400/512: year=2020 aai=0.011

[lisbon] sample 401/512: year=2030 aai=0.000

[lisbon] sample 402/512: year=2040 aai=0.267

[lisbon] sample 403/512: year=2050 aai=1.247

[lisbon] sample 404/512: year=2030 aai=0.000

[lisbon] sample 405/512: year=2030 aai=0.040

[lisbon] sample 406/512: year=2030 aai=0.004

[lisbon] sample 407/512: year=2050 aai=0.005

[lisbon] sample 408/512: year=2050 aai=0.026

[lisbon] sample 409/512: year=2040 aai=0.167

[lisbon] sample 410/512: year=2050 aai=0.028

[lisbon] sample 411/512: year=2050 aai=0.037

[lisbon] sample 412/512: year=2050 aai=0.000

[lisbon] sample 413/512: year=2040 aai=0.049

[lisbon] sample 414/512: year=2050 aai=0.309

[lisbon] sample 415/512: year=2050 aai=0.428

[lisbon] sample 416/512: year=2040 aai=0.133

[lisbon] sample 417/512: year=2050 aai=0.173

[lisbon] sample 418/512: year=2030 aai=0.170

[lisbon] sample 419/512: year=2030 aai=0.006

[lisbon] sample 420/512: year=2030 aai=0.018

[lisbon] sample 421/512: year=2050 aai=0.046

[lisbon] sample 422/512: year=2030 aai=0.505

[lisbon] sample 423/512: year=2030 aai=0.399

[lisbon] sample 424/512: year=2050 aai=0.076

[lisbon] sample 425/512: year=2050 aai=0.413

[lisbon] sample 426/512: year=2050 aai=0.393

[lisbon] sample 427/512: year=2050 aai=0.005

[lisbon] sample 428/512: year=2050 aai=0.000

[lisbon] sample 429/512: year=2040 aai=0.173

[lisbon] sample 430/512: year=2050 aai=0.037

[lisbon] sample 431/512: year=2030 aai=0.031

[lisbon] sample 432/512: year=2050 aai=0.000

[lisbon] sample 433/512: year=2020 aai=0.320

[lisbon] sample 434/512: year=2040 aai=0.470

[lisbon] sample 435/512: year=2040 aai=0.004

[lisbon] sample 436/512: year=2030 aai=0.070

[lisbon] sample 437/512: year=2030 aai=0.000

[lisbon] sample 438/512: year=2020 aai=0.016

[lisbon] sample 439/512: year=2050 aai=0.021

[lisbon] sample 440/512: year=2030 aai=0.003

[lisbon] sample 441/512: year=2020 aai=0.420

[lisbon] sample 442/512: year=2020 aai=0.049

[lisbon] sample 443/512: year=2030 aai=0.021

[lisbon] sample 444/512: year=2020 aai=0.322

[lisbon] sample 445/512: year=2050 aai=0.036

[lisbon] sample 446/512: year=2040 aai=0.000

[lisbon] sample 447/512: year=2040 aai=0.009

[lisbon] sample 448/512: year=2040 aai=0.370

[lisbon] sample 449/512: year=2030 aai=0.004

[lisbon] sample 450/512: year=2030 aai=0.042

[lisbon] sample 451/512: year=2050 aai=0.004

[lisbon] sample 452/512: year=2050 aai=0.000

[lisbon] sample 453/512: year=2040 aai=0.361

[lisbon] sample 454/512: year=2030 aai=0.006

[lisbon] sample 455/512: year=2050 aai=0.112

[lisbon] sample 456/512: year=2030 aai=0.004

[lisbon] sample 457/512: year=2020 aai=0.118

[lisbon] sample 458/512: year=2040 aai=0.306

[lisbon] sample 459/512: year=2020 aai=0.102

[lisbon] sample 460/512: year=2050 aai=0.002

[lisbon] sample 461/512: year=2030 aai=0.017

[lisbon] sample 462/512: year=2050 aai=0.005

[lisbon] sample 463/512: year=2040 aai=0.281

[lisbon] sample 464/512: year=2050 aai=0.082

[lisbon] sample 465/512: year=2020 aai=0.019

[lisbon] sample 466/512: year=2020 aai=0.144

[lisbon] sample 467/512: year=2040 aai=0.408

[lisbon] sample 468/512: year=2020 aai=0.000

[lisbon] sample 469/512: year=2040 aai=0.003

[lisbon] sample 470/512: year=2050 aai=0.329

[lisbon] sample 471/512: year=2040 aai=0.157

[lisbon] sample 472/512: year=2020 aai=0.277

[lisbon] sample 473/512: year=2050 aai=0.124

[lisbon] sample 474/512: year=2020 aai=0.000

[lisbon] sample 475/512: year=2020 aai=0.041

[lisbon] sample 476/512: year=2030 aai=0.090

[lisbon] sample 477/512: year=2030 aai=0.308

[lisbon] sample 478/512: year=2030 aai=0.095

[lisbon] sample 479/512: year=2050 aai=0.003

[lisbon] sample 480/512: year=2030 aai=0.362

[lisbon] sample 481/512: year=2050 aai=0.006

[lisbon] sample 482/512: year=2030 aai=0.000

[lisbon] sample 483/512: year=2040 aai=0.035

[lisbon] sample 484/512: year=2040 aai=0.028

[lisbon] sample 485/512: year=2020 aai=0.048

[lisbon] sample 486/512: year=2040 aai=0.000

[lisbon] sample 487/512: year=2050 aai=0.008

[lisbon] sample 488/512: year=2020 aai=0.016

[lisbon] sample 489/512: year=2030 aai=0.041

[lisbon] sample 490/512: year=2040 aai=0.073

[lisbon] sample 491/512: year=2020 aai=0.378

[lisbon] sample 492/512: year=2030 aai=0.090

[lisbon] sample 493/512: year=2040 aai=0.083

[lisbon] sample 494/512: year=2020 aai=0.100

[lisbon] sample 495/512: year=2040 aai=0.329

[lisbon] sample 496/512: year=2020 aai=0.000

[lisbon] sample 497/512: year=2050 aai=0.138

[lisbon] sample 498/512: year=2030 aai=1.033

[lisbon] sample 499/512: year=2020 aai=0.019

[lisbon] sample 500/512: year=2050 aai=0.241

[lisbon] sample 501/512: year=2040 aai=0.119

[lisbon] sample 502/512: year=2050 aai=0.000

[lisbon] sample 503/512: year=2040 aai=0.372

[lisbon] sample 504/512: year=2020 aai=0.000

[lisbon] sample 505/512: year=2030 aai=0.008

[lisbon] sample 506/512: year=2030 aai=0.023

[lisbon] sample 507/512: year=2040 aai=0.000

[lisbon] sample 508/512: year=2040 aai=0.179

[lisbon] sample 509/512: year=2040 aai=0.018

[lisbon] sample 510/512: year=2030 aai=0.005

[lisbon] sample 511/512: year=2040 aai=0.161

[lisbon] sample 512/512: year=2030 aai=0.003

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))
/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

{'samples': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/unc_samples_lisbon_improved.csv'),
 'impact': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/unc_impact_summary_lisbon_improved.csv'),
 'freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/unc_freq_curve_lisbon_improved.csv'),
 'cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/unc_cba_ews_lisbon_improved.csv'),
 'vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/unc_vulnerability_lisbon_improved.csv'),
 'sens_aai': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/sens_aai_agg_lisbon_improved.csv'),
 'sens_freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/sens_freq_curve_lisbon_improved.csv'),
 'sens_cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/sens_cba_ews_lisbon_improved.csv'),
 'sens_vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/sens_vulnerability_lisbon_improved.csv'),
 'meta': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/uq_dimensions_lisbon_improved.json'),
 'bundle': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/unc_impact_lisbon_march2026_improved.h5'),
 'bundle_sens': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/lisbon/tables/uncertainty_improved/unc_impact_lisbon_march2026_improved_with_sensitivity.h5')}

In [3]:
import pandas as pd

samples = pd.read_csv(paths['samples'])
samples[[
    'year', 'aai_agg', 'annual_deaths', 'sample_warning_days',
    'sample_threshold_deaths_per_day', 'ews_pv_cost_25y',
    'ews_net_avoided_deaths_25y_cum', 'ews_cost_per_net_death_25y_cum'
]].head(10)

,year,aai_agg,annual_deaths,sample_warning_days,sample_threshold_deaths_per_day,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_cost_per_net_death_25y_cum
0,2050,0.519832,189.738861,30.0,2.074731e+00,1.951106e+06,108.798596,17933.187155
1,2030,0.093372,34.080653,27.0,4.922810e-01,1.125401e+07,105.773841,106396.869371
2,2040,0.318131,116.435847,23.0,1.496310e+00,8.117675e+06,72.616716,111787.965826
3,2020,0.003106,1.136732,15.0,4.813357e-03,6.164331e+06,6.506710,947380.695171
4,2020,0.456823,167.197133,23.0,2.193256e+00,2.547116e+06,536.090121,4751.283257
5,2030,0.123986,45.254875,23.0,5.908756e-01,1.018361e+07,22.612410,450354.878822
6,2040,0.030504,11.164387,37.0,1.165881e-01,1.165312e+07,22.619859,515172.177031
7,2050,0.008942,3.263994,31.0,2.523403e-08,8.886695e+06,9.807494,906112.698621
8,2020,0.306761,112.274585,15.0,2.279441e+00,7.546528e+06,125.650844,60059.511285
9,2040,0.152141,55.683439,15.0,1.276836e+00,5.062506e+06,142.602352,35500.860401

In [4]:
impact_summary = pd.read_csv(paths['impact'])
cba_summary = pd.read_csv(paths['cba'])

display(impact_summary.describe())
display(cba_summary.describe())

,aai_agg,annual_deaths,rp2,rp5,rp10,rp20
count,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000
mean,0.144906,52.961323,0.007755,0.184343,0.430757,0.757894
std,0.208688,76.262204,0.039237,0.344506,0.662648,0.995005
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.008604,3.146780,0.000000,0.000000,0.000726,0.022527
50%,0.052109,19.071928,0.000000,0.011998,0.109039,0.323652
75%,0.183682,67.227578,0.000000,0.246739,0.579034,1.048114
max,1.247331,456.091847,0.374361,2.194737,3.918932,5.349417

,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_net_avoided_deaths_25y_pv,ews_cost_per_net_death_25y_cum,ews_cost_per_net_death_25y_pv,ews_life_years_saved_25y_cum
count,5.120000e+02,512.000000,512.000000,5.120000e+02,5.120000e+02,512.000000
mean,8.474108e+06,63.403053,41.826604,inf,inf,824.908363
std,1.122172e+07,95.255779,62.696523,NaN,NaN,1247.266860
min,1.088287e+06,0.000000,0.000000,2.894665e+03,4.455375e+03,0.000000
25%,2.323347e+06,6.754563,4.473114,5.112429e+04,7.767830e+04,85.824193
50%,6.156218e+06,24.947791,16.315864,1.877762e+05,2.850720e+05,327.061816
75%,9.646281e+06,81.469926,53.960300,7.788854e+05,1.176384e+06,1061.098017
max,6.170051e+07,619.313050,406.072190,inf,inf,8145.623774