# Notebook 09 - Uncertainty Quantification (Second version)

City-agnostic improved workflow for **Athens**. This version keeps the
original March 2026 `NB09` untouched and adds three targeted
improvements: 
- spatially explicit daily raster modifiers for trees and
waste heat
- event-level warning-day logic for EWS
- EWS CBA uncertainty
outputs alongside the impact uncertainty outputs

All new outputs are written to
`outputs/athens/tables/uncertainty_improved/` so the original `NB09`
outputs remain unchanged.

In [1]:
import os
import sys
from pathlib import Path

os.environ.setdefault('CITY', 'athens')
os.environ.setdefault('NB09_N', '512')
os.environ.setdefault('NB09_SEED', '42')

def _find_repo_root():
    env = os.environ.get("URBAN_HEAT_ROOT")
    if env:
        root = Path(env).expanduser().resolve()
        if (root / "cityheat").is_dir() and (root / "configs").is_dir():
            return root
    start = Path.cwd().resolve()
    for cand in [start, *start.parents]:
        if (cand / "cityheat").is_dir() and (cand / "configs").is_dir():
            return cand
    raise RuntimeError(
        "Could not locate repo root. Run the notebook from inside the repo "
        "or set URBAN_HEAT_ROOT."
    )

ROOT = _find_repo_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print('ROOT:', ROOT)
print('CITY:', os.environ['CITY'])
print('NB09_N:', os.environ['NB09_N'])
print('NB09_SEED:', os.environ['NB09_SEED'])

ROOT: /Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat
CITY: athens
NB09_N: 512
NB09_SEED: 42

In [2]:
from cityheat.nb09_improved import run_nb09_improved

paths = run_nb09_improved()
paths

Matplotlib is building the font cache; this may take a moment.

[athens] sample 1/512: year=2050 aai=4.916

[athens] sample 2/512: year=2030 aai=1.530

[athens] sample 3/512: year=2040 aai=3.210

[athens] sample 4/512: year=2020 aai=0.119

[athens] sample 5/512: year=2020 aai=4.721

[athens] sample 6/512: year=2030 aai=1.041

[athens] sample 7/512: year=2040 aai=1.930

[athens] sample 8/512: year=2050 aai=0.237

[athens] sample 9/512: year=2020 aai=2.276

[athens] sample 10/512: year=2040 aai=1.741

[athens] sample 11/512: year=2040 aai=0.451

[athens] sample 12/512: year=2020 aai=0.535

[athens] sample 13/512: year=2040 aai=0.542

[athens] sample 14/512: year=2020 aai=3.402

[athens] sample 15/512: year=2040 aai=7.083

[athens] sample 16/512: year=2050 aai=0.364

[athens] sample 17/512: year=2020 aai=3.946

[athens] sample 18/512: year=2050 aai=0.509

[athens] sample 19/512: year=2040 aai=4.037

[athens] sample 20/512: year=2020 aai=0.989

[athens] sample 21/512: year=2020 aai=3.745

[athens] sample 22/512: year=2050 aai=0.329

[athens] sample 23/512: year=2020 aai=1.932

[athens] sample 24/512: year=2030 aai=1.693

[athens] sample 25/512: year=2050 aai=2.154

[athens] sample 26/512: year=2030 aai=1.661

[athens] sample 27/512: year=2020 aai=0.234

[athens] sample 28/512: year=2050 aai=2.801

[athens] sample 29/512: year=2030 aai=1.865

[athens] sample 30/512: year=2030 aai=2.049

[athens] sample 31/512: year=2020 aai=3.410

[athens] sample 32/512: year=2030 aai=1.727

[athens] sample 33/512: year=2020 aai=2.370

[athens] sample 34/512: year=2020 aai=3.485

[athens] sample 35/512: year=2040 aai=0.421

[athens] sample 36/512: year=2040 aai=2.624

[athens] sample 37/512: year=2040 aai=0.173

[athens] sample 38/512: year=2050 aai=4.983

[athens] sample 39/512: year=2040 aai=3.386

[athens] sample 40/512: year=2050 aai=2.834

[athens] sample 41/512: year=2030 aai=0.533

[athens] sample 42/512: year=2020 aai=3.026

[athens] sample 43/512: year=2020 aai=0.739

[athens] sample 44/512: year=2040 aai=1.447

[athens] sample 45/512: year=2050 aai=1.093

[athens] sample 46/512: year=2050 aai=0.938

[athens] sample 47/512: year=2040 aai=2.065

[athens] sample 48/512: year=2040 aai=0.399

[athens] sample 49/512: year=2030 aai=1.214

[athens] sample 50/512: year=2040 aai=2.685

[athens] sample 51/512: year=2020 aai=0.040

[athens] sample 52/512: year=2050 aai=2.049

[athens] sample 53/512: year=2040 aai=6.425

[athens] sample 54/512: year=2020 aai=0.807

[athens] sample 55/512: year=2050 aai=3.449

[athens] sample 56/512: year=2040 aai=1.514

[athens] sample 57/512: year=2030 aai=2.517

[athens] sample 58/512: year=2020 aai=1.673

[athens] sample 59/512: year=2020 aai=1.246

[athens] sample 60/512: year=2040 aai=0.071

[athens] sample 61/512: year=2040 aai=1.468

[athens] sample 62/512: year=2050 aai=7.181

[athens] sample 63/512: year=2050 aai=0.748

[athens] sample 64/512: year=2040 aai=3.992

[athens] sample 65/512: year=2020 aai=0.836

[athens] sample 66/512: year=2030 aai=3.107

[athens] sample 67/512: year=2030 aai=2.732

[athens] sample 68/512: year=2050 aai=0.400

[athens] sample 69/512: year=2020 aai=0.434

[athens] sample 70/512: year=2040 aai=0.088

[athens] sample 71/512: year=2050 aai=2.970

[athens] sample 72/512: year=2030 aai=0.972

[athens] sample 73/512: year=2030 aai=0.642

[athens] sample 74/512: year=2030 aai=3.564

[athens] sample 75/512: year=2020 aai=0.384

[athens] sample 76/512: year=2020 aai=3.727

[athens] sample 77/512: year=2020 aai=0.045

[athens] sample 78/512: year=2050 aai=2.086

[athens] sample 79/512: year=2050 aai=0.273

[athens] sample 80/512: year=2050 aai=1.120

[athens] sample 81/512: year=2020 aai=2.478

[athens] sample 82/512: year=2050 aai=2.571

[athens] sample 83/512: year=2020 aai=1.036

[athens] sample 84/512: year=2020 aai=0.174

[athens] sample 85/512: year=2050 aai=0.409

[athens] sample 86/512: year=2050 aai=2.944

[athens] sample 87/512: year=2050 aai=2.255

[athens] sample 88/512: year=2020 aai=3.118

[athens] sample 89/512: year=2040 aai=5.295

[athens] sample 90/512: year=2040 aai=0.267

[athens] sample 91/512: year=2020 aai=0.223

[athens] sample 92/512: year=2030 aai=0.100

[athens] sample 93/512: year=2030 aai=2.070

[athens] sample 94/512: year=2030 aai=1.001

[athens] sample 95/512: year=2030 aai=0.458

[athens] sample 96/512: year=2020 aai=0.171

[athens] sample 97/512: year=2050 aai=2.011

[athens] sample 98/512: year=2030 aai=0.227

[athens] sample 99/512: year=2040 aai=2.029

[athens] sample 100/512: year=2020 aai=0.946

[athens] sample 101/512: year=2030 aai=0.353

[athens] sample 102/512: year=2040 aai=2.471

[athens] sample 103/512: year=2040 aai=0.072

[athens] sample 104/512: year=2030 aai=1.363

[athens] sample 105/512: year=2030 aai=1.579

[athens] sample 106/512: year=2050 aai=0.516

[athens] sample 107/512: year=2020 aai=0.836

[athens] sample 108/512: year=2040 aai=1.499

[athens] sample 109/512: year=2050 aai=0.752

[athens] sample 110/512: year=2020 aai=1.482

[athens] sample 111/512: year=2040 aai=0.782

[athens] sample 112/512: year=2030 aai=0.833

[athens] sample 113/512: year=2020 aai=1.904

[athens] sample 114/512: year=2030 aai=1.409

[athens] sample 115/512: year=2020 aai=2.986

[athens] sample 116/512: year=2050 aai=2.724

[athens] sample 117/512: year=2030 aai=0.407

[athens] sample 118/512: year=2050 aai=1.180

[athens] sample 119/512: year=2030 aai=4.261

[athens] sample 120/512: year=2020 aai=1.202

[athens] sample 121/512: year=2020 aai=4.767

[athens] sample 122/512: year=2040 aai=6.806

[athens] sample 123/512: year=2030 aai=0.947

[athens] sample 124/512: year=2040 aai=0.453

[athens] sample 125/512: year=2020 aai=2.964

[athens] sample 126/512: year=2020 aai=1.993

[athens] sample 127/512: year=2040 aai=2.796

[athens] sample 128/512: year=2030 aai=0.209

[athens] sample 129/512: year=2030 aai=2.226

[athens] sample 130/512: year=2020 aai=3.153

[athens] sample 131/512: year=2030 aai=0.250

[athens] sample 132/512: year=2050 aai=2.130

[athens] sample 133/512: year=2030 aai=0.499

[athens] sample 134/512: year=2050 aai=0.622

[athens] sample 135/512: year=2040 aai=2.139

[athens] sample 136/512: year=2030 aai=4.990

[athens] sample 137/512: year=2050 aai=6.452

[athens] sample 138/512: year=2020 aai=0.650

[athens] sample 139/512: year=2020 aai=2.887

[athens] sample 140/512: year=2050 aai=0.226

[athens] sample 141/512: year=2030 aai=0.471

[athens] sample 142/512: year=2020 aai=1.934

[athens] sample 143/512: year=2040 aai=0.214

[athens] sample 144/512: year=2050 aai=4.110

[athens] sample 145/512: year=2020 aai=0.150

[athens] sample 146/512: year=2030 aai=0.245

[athens] sample 147/512: year=2050 aai=1.580

[athens] sample 148/512: year=2020 aai=0.550

[athens] sample 149/512: year=2020 aai=0.737

[athens] sample 150/512: year=2030 aai=3.607

[athens] sample 151/512: year=2040 aai=3.142

[athens] sample 152/512: year=2040 aai=4.466

[athens] sample 153/512: year=2030 aai=0.054

[athens] sample 154/512: year=2050 aai=1.860

[athens] sample 155/512: year=2020 aai=0.580

[athens] sample 156/512: year=2020 aai=0.866

[athens] sample 157/512: year=2040 aai=0.198

[athens] sample 158/512: year=2050 aai=0.767

[athens] sample 159/512: year=2050 aai=0.611

[athens] sample 160/512: year=2040 aai=2.330

[athens] sample 161/512: year=2040 aai=1.791

[athens] sample 162/512: year=2050 aai=2.742

[athens] sample 163/512: year=2040 aai=1.349

[athens] sample 164/512: year=2030 aai=8.488

[athens] sample 165/512: year=2030 aai=3.621

[athens] sample 166/512: year=2030 aai=5.302

[athens] sample 167/512: year=2050 aai=0.902

[athens] sample 168/512: year=2040 aai=1.230

[athens] sample 169/512: year=2040 aai=2.794

[athens] sample 170/512: year=2050 aai=0.375

[athens] sample 171/512: year=2020 aai=1.204

[athens] sample 172/512: year=2040 aai=0.882

[athens] sample 173/512: year=2020 aai=1.512

[athens] sample 174/512: year=2030 aai=0.340

[athens] sample 175/512: year=2040 aai=0.311

[athens] sample 176/512: year=2030 aai=2.426

[athens] sample 177/512: year=2040 aai=0.867

[athens] sample 178/512: year=2040 aai=2.774

[athens] sample 179/512: year=2050 aai=0.229

[athens] sample 180/512: year=2050 aai=6.539

[athens] sample 181/512: year=2050 aai=0.269

[athens] sample 182/512: year=2020 aai=0.537

[athens] sample 183/512: year=2040 aai=0.740

[athens] sample 184/512: year=2020 aai=0.906

[athens] sample 185/512: year=2030 aai=0.732

[athens] sample 186/512: year=2040 aai=1.793

[athens] sample 187/512: year=2040 aai=8.005

[athens] sample 188/512: year=2040 aai=0.602

[athens] sample 189/512: year=2030 aai=1.275

[athens] sample 190/512: year=2030 aai=3.284

[athens] sample 191/512: year=2030 aai=1.300

[athens] sample 192/512: year=2040 aai=1.829

[athens] sample 193/512: year=2020 aai=1.349

[athens] sample 194/512: year=2030 aai=1.817

[athens] sample 195/512: year=2020 aai=0.902

[athens] sample 196/512: year=2050 aai=5.206

[athens] sample 197/512: year=2020 aai=5.850

[athens] sample 198/512: year=2020 aai=0.159

[athens] sample 199/512: year=2050 aai=1.460

[athens] sample 200/512: year=2040 aai=0.219

[athens] sample 201/512: year=2050 aai=0.669

[athens] sample 202/512: year=2030 aai=0.273

[athens] sample 203/512: year=2020 aai=0.078

[athens] sample 204/512: year=2050 aai=3.052

[athens] sample 205/512: year=2040 aai=1.802

[athens] sample 206/512: year=2020 aai=2.075

[athens] sample 207/512: year=2040 aai=0.161

[athens] sample 208/512: year=2030 aai=0.264

[athens] sample 209/512: year=2020 aai=0.084

[athens] sample 210/512: year=2030 aai=5.480

[athens] sample 211/512: year=2030 aai=0.399

[athens] sample 212/512: year=2050 aai=0.116

[athens] sample 213/512: year=2040 aai=0.558

[athens] sample 214/512: year=2040 aai=1.791

[athens] sample 215/512: year=2030 aai=0.142

[athens] sample 216/512: year=2030 aai=0.527

[athens] sample 217/512: year=2020 aai=0.147

[athens] sample 218/512: year=2020 aai=2.030

[athens] sample 219/512: year=2020 aai=4.078

[athens] sample 220/512: year=2050 aai=0.251

[athens] sample 221/512: year=2050 aai=1.734

[athens] sample 222/512: year=2040 aai=1.103

[athens] sample 223/512: year=2040 aai=0.366

[athens] sample 224/512: year=2040 aai=0.712

[athens] sample 225/512: year=2050 aai=1.542

[athens] sample 226/512: year=2020 aai=6.708

[athens] sample 227/512: year=2030 aai=0.611

[athens] sample 228/512: year=2030 aai=1.496

[athens] sample 229/512: year=2040 aai=1.278

[athens] sample 230/512: year=2050 aai=0.923

[athens] sample 231/512: year=2030 aai=0.284

[athens] sample 232/512: year=2050 aai=0.473

[athens] sample 233/512: year=2030 aai=6.104

[athens] sample 234/512: year=2020 aai=2.222

[athens] sample 235/512: year=2020 aai=0.243

[athens] sample 236/512: year=2050 aai=0.164

[athens] sample 237/512: year=2050 aai=5.185

[athens] sample 238/512: year=2020 aai=1.693

[athens] sample 239/512: year=2040 aai=3.550

[athens] sample 240/512: year=2050 aai=0.103

[athens] sample 241/512: year=2040 aai=1.372

[athens] sample 242/512: year=2040 aai=0.446

[athens] sample 243/512: year=2030 aai=0.956

[athens] sample 244/512: year=2040 aai=1.534

[athens] sample 245/512: year=2050 aai=0.575

[athens] sample 246/512: year=2050 aai=1.645

[athens] sample 247/512: year=2040 aai=0.048

[athens] sample 248/512: year=2020 aai=5.368

[athens] sample 249/512: year=2030 aai=4.880

[athens] sample 250/512: year=2040 aai=0.332

[athens] sample 251/512: year=2050 aai=0.082

[athens] sample 252/512: year=2030 aai=0.122

[athens] sample 253/512: year=2020 aai=0.229

[athens] sample 254/512: year=2050 aai=0.274

[athens] sample 255/512: year=2040 aai=0.154

[athens] sample 256/512: year=2040 aai=2.191

[athens] sample 257/512: year=2020 aai=0.622

[athens] sample 258/512: year=2020 aai=2.526

[athens] sample 259/512: year=2030 aai=0.192

[athens] sample 260/512: year=2040 aai=0.361

[athens] sample 261/512: year=2020 aai=0.695

[athens] sample 262/512: year=2050 aai=1.143

[athens] sample 263/512: year=2050 aai=1.412

[athens] sample 264/512: year=2020 aai=2.350

[athens] sample 265/512: year=2020 aai=0.750

[athens] sample 266/512: year=2050 aai=1.232

[athens] sample 267/512: year=2030 aai=1.787

[athens] sample 268/512: year=2030 aai=0.819

[athens] sample 269/512: year=2020 aai=0.302

[athens] sample 270/512: year=2040 aai=0.229

[athens] sample 271/512: year=2050 aai=4.175

[athens] sample 272/512: year=2040 aai=3.032

[athens] sample 273/512: year=2040 aai=0.048

[athens] sample 274/512: year=2040 aai=3.654

[athens] sample 275/512: year=2030 aai=0.436

[athens] sample 276/512: year=2030 aai=0.506

[athens] sample 277/512: year=2040 aai=0.869

[athens] sample 278/512: year=2020 aai=0.907

[athens] sample 279/512: year=2020 aai=0.232

[athens] sample 280/512: year=2050 aai=4.487

[athens] sample 281/512: year=2050 aai=4.509

[athens] sample 282/512: year=2030 aai=3.962

[athens] sample 283/512: year=2020 aai=0.198

[athens] sample 284/512: year=2020 aai=0.161

[athens] sample 285/512: year=2040 aai=0.670

[athens] sample 286/512: year=2030 aai=2.204

[athens] sample 287/512: year=2030 aai=3.883

[athens] sample 288/512: year=2030 aai=0.065

[athens] sample 289/512: year=2040 aai=1.354

[athens] sample 290/512: year=2050 aai=0.339

[athens] sample 291/512: year=2040 aai=0.551

[athens] sample 292/512: year=2050 aai=1.194

[athens] sample 293/512: year=2030 aai=0.165

[athens] sample 294/512: year=2050 aai=4.142

[athens] sample 295/512: year=2040 aai=2.479

[athens] sample 296/512: year=2020 aai=0.541

[athens] sample 297/512: year=2050 aai=0.628

[athens] sample 298/512: year=2040 aai=0.796

[athens] sample 299/512: year=2040 aai=0.941

[athens] sample 300/512: year=2020 aai=1.033

[athens] sample 301/512: year=2050 aai=4.356

[athens] sample 302/512: year=2050 aai=0.415

[athens] sample 303/512: year=2040 aai=0.253

[athens] sample 304/512: year=2030 aai=1.552

[athens] sample 305/512: year=2020 aai=0.637

[athens] sample 306/512: year=2030 aai=0.130

[athens] sample 307/512: year=2040 aai=2.289

[athens] sample 308/512: year=2050 aai=2.367

[athens] sample 309/512: year=2030 aai=0.812

[athens] sample 310/512: year=2030 aai=0.173

[athens] sample 311/512: year=2020 aai=1.413

[athens] sample 312/512: year=2020 aai=0.293

[athens] sample 313/512: year=2030 aai=3.381

[athens] sample 314/512: year=2050 aai=0.238

[athens] sample 315/512: year=2020 aai=2.810

[athens] sample 316/512: year=2040 aai=5.543

[athens] sample 317/512: year=2040 aai=0.682

[athens] sample 318/512: year=2040 aai=1.053

[athens] sample 319/512: year=2040 aai=1.661

[athens] sample 320/512: year=2040 aai=1.951

[athens] sample 321/512: year=2050 aai=0.627

[athens] sample 322/512: year=2040 aai=0.384

[athens] sample 323/512: year=2040 aai=0.904

[athens] sample 324/512: year=2040 aai=0.174

[athens] sample 325/512: year=2030 aai=2.892

[athens] sample 326/512: year=2040 aai=0.360

[athens] sample 327/512: year=2030 aai=1.177

[athens] sample 328/512: year=2050 aai=0.227

[athens] sample 329/512: year=2040 aai=0.343

[athens] sample 330/512: year=2040 aai=0.322

[athens] sample 331/512: year=2030 aai=0.740

[athens] sample 332/512: year=2050 aai=0.232

[athens] sample 333/512: year=2030 aai=0.722

[athens] sample 334/512: year=2030 aai=0.077

[athens] sample 335/512: year=2020 aai=1.008

[athens] sample 336/512: year=2040 aai=0.529

[athens] sample 337/512: year=2050 aai=0.185

[athens] sample 338/512: year=2040 aai=9.239

[athens] sample 339/512: year=2040 aai=0.589

[athens] sample 340/512: year=2020 aai=0.044

[athens] sample 341/512: year=2020 aai=0.362

[athens] sample 342/512: year=2030 aai=2.535

[athens] sample 343/512: year=2040 aai=0.583

[athens] sample 344/512: year=2050 aai=0.205

[athens] sample 345/512: year=2020 aai=4.133

[athens] sample 346/512: year=2050 aai=0.250

[athens] sample 347/512: year=2050 aai=3.149

[athens] sample 348/512: year=2030 aai=2.868

[athens] sample 349/512: year=2020 aai=0.377

[athens] sample 350/512: year=2030 aai=2.697

[athens] sample 351/512: year=2030 aai=2.848

[athens] sample 352/512: year=2020 aai=0.453

[athens] sample 353/512: year=2030 aai=1.077

[athens] sample 354/512: year=2050 aai=1.743

[athens] sample 355/512: year=2020 aai=0.401

[athens] sample 356/512: year=2030 aai=0.174

[athens] sample 357/512: year=2050 aai=5.667

[athens] sample 358/512: year=2020 aai=0.250

[athens] sample 359/512: year=2050 aai=0.334

[athens] sample 360/512: year=2030 aai=2.291

[athens] sample 361/512: year=2020 aai=0.427

[athens] sample 362/512: year=2020 aai=0.765

[athens] sample 363/512: year=2030 aai=0.448

[athens] sample 364/512: year=2030 aai=1.856

[athens] sample 365/512: year=2020 aai=1.530

[athens] sample 366/512: year=2040 aai=1.268

[athens] sample 367/512: year=2020 aai=1.658

[athens] sample 368/512: year=2030 aai=0.919

[athens] sample 369/512: year=2030 aai=0.221

[athens] sample 370/512: year=2020 aai=1.882

[athens] sample 371/512: year=2050 aai=0.433

[athens] sample 372/512: year=2050 aai=2.005

[athens] sample 373/512: year=2020 aai=1.118

[athens] sample 374/512: year=2020 aai=0.918

[athens] sample 375/512: year=2030 aai=0.595

[athens] sample 376/512: year=2020 aai=1.118

[athens] sample 377/512: year=2050 aai=0.437

[athens] sample 378/512: year=2020 aai=0.985

[athens] sample 379/512: year=2020 aai=2.577

[athens] sample 380/512: year=2030 aai=1.342

[athens] sample 381/512: year=2040 aai=1.502

[athens] sample 382/512: year=2020 aai=0.644

[athens] sample 383/512: year=2020 aai=0.404

[athens] sample 384/512: year=2050 aai=1.078

[athens] sample 385/512: year=2040 aai=0.804

[athens] sample 386/512: year=2030 aai=0.748

[athens] sample 387/512: year=2050 aai=2.701

[athens] sample 388/512: year=2020 aai=0.059

[athens] sample 389/512: year=2030 aai=0.885

[athens] sample 390/512: year=2040 aai=0.939

[athens] sample 391/512: year=2050 aai=1.818

[athens] sample 392/512: year=2050 aai=0.725

[athens] sample 393/512: year=2020 aai=0.546

[athens] sample 394/512: year=2050 aai=0.490

[athens] sample 395/512: year=2050 aai=2.150

[athens] sample 396/512: year=2020 aai=1.010

[athens] sample 397/512: year=2030 aai=0.424

[athens] sample 398/512: year=2050 aai=4.896

[athens] sample 399/512: year=2030 aai=0.486

[athens] sample 400/512: year=2020 aai=0.534

[athens] sample 401/512: year=2030 aai=0.075

[athens] sample 402/512: year=2040 aai=2.420

[athens] sample 403/512: year=2050 aai=7.309

[athens] sample 404/512: year=2030 aai=0.041

[athens] sample 405/512: year=2030 aai=1.218

[athens] sample 406/512: year=2030 aai=0.809

[athens] sample 407/512: year=2050 aai=0.205

[athens] sample 408/512: year=2050 aai=0.443

[athens] sample 409/512: year=2040 aai=2.109

[athens] sample 410/512: year=2050 aai=0.478

[athens] sample 411/512: year=2050 aai=0.938

[athens] sample 412/512: year=2050 aai=0.204

[athens] sample 413/512: year=2040 aai=2.138

[athens] sample 414/512: year=2050 aai=2.257

[athens] sample 415/512: year=2050 aai=3.364

[athens] sample 416/512: year=2040 aai=1.878

[athens] sample 417/512: year=2050 aai=2.159

[athens] sample 418/512: year=2030 aai=2.329

[athens] sample 419/512: year=2030 aai=0.270

[athens] sample 420/512: year=2030 aai=0.529

[athens] sample 421/512: year=2050 aai=1.304

[athens] sample 422/512: year=2030 aai=3.842

[athens] sample 423/512: year=2030 aai=3.925

[athens] sample 424/512: year=2050 aai=1.295

[athens] sample 425/512: year=2050 aai=3.165

[athens] sample 426/512: year=2050 aai=3.806

[athens] sample 427/512: year=2050 aai=0.639

[athens] sample 428/512: year=2050 aai=0.175

[athens] sample 429/512: year=2040 aai=2.125

[athens] sample 430/512: year=2050 aai=0.811

[athens] sample 431/512: year=2030 aai=1.236

[athens] sample 432/512: year=2050 aai=0.073

[athens] sample 433/512: year=2020 aai=3.478

[athens] sample 434/512: year=2040 aai=4.079

[athens] sample 435/512: year=2040 aai=0.169

[athens] sample 436/512: year=2030 aai=1.551

[athens] sample 437/512: year=2030 aai=0.057

[athens] sample 438/512: year=2020 aai=0.408

[athens] sample 439/512: year=2050 aai=0.913

[athens] sample 440/512: year=2030 aai=0.401

[athens] sample 441/512: year=2020 aai=4.423

[athens] sample 442/512: year=2020 aai=0.661

[athens] sample 443/512: year=2030 aai=0.469

[athens] sample 444/512: year=2020 aai=2.597

[athens] sample 445/512: year=2050 aai=0.646

[athens] sample 446/512: year=2040 aai=0.080

[athens] sample 447/512: year=2040 aai=0.495

[athens] sample 448/512: year=2040 aai=3.735

[athens] sample 449/512: year=2030 aai=0.139

[athens] sample 450/512: year=2030 aai=1.038

[athens] sample 451/512: year=2050 aai=0.174

[athens] sample 452/512: year=2050 aai=0.071

[athens] sample 453/512: year=2040 aai=3.149

[athens] sample 454/512: year=2030 aai=0.288

[athens] sample 455/512: year=2050 aai=1.027

[athens] sample 456/512: year=2030 aai=0.180

[athens] sample 457/512: year=2020 aai=1.218

[athens] sample 458/512: year=2040 aai=2.334

[athens] sample 459/512: year=2020 aai=1.667

[athens] sample 460/512: year=2050 aai=0.427

[athens] sample 461/512: year=2030 aai=0.437

[athens] sample 462/512: year=2050 aai=0.688

[athens] sample 463/512: year=2040 aai=2.346

[athens] sample 464/512: year=2050 aai=1.135

[athens] sample 465/512: year=2020 aai=0.490

[athens] sample 466/512: year=2020 aai=1.572

[athens] sample 467/512: year=2040 aai=4.118

[athens] sample 468/512: year=2020 aai=0.086

[athens] sample 469/512: year=2040 aai=0.439

[athens] sample 470/512: year=2050 aai=2.953

[athens] sample 471/512: year=2040 aai=2.172

[athens] sample 472/512: year=2020 aai=2.883

[athens] sample 473/512: year=2050 aai=1.972

[athens] sample 474/512: year=2020 aai=0.166

[athens] sample 475/512: year=2020 aai=0.698

[athens] sample 476/512: year=2030 aai=0.969

[athens] sample 477/512: year=2030 aai=2.564

[athens] sample 478/512: year=2030 aai=1.987

[athens] sample 479/512: year=2050 aai=0.423

[athens] sample 480/512: year=2030 aai=3.447

[athens] sample 481/512: year=2050 aai=0.303

[athens] sample 482/512: year=2030 aai=0.129

[athens] sample 483/512: year=2040 aai=1.119

[athens] sample 484/512: year=2040 aai=0.794

[athens] sample 485/512: year=2020 aai=0.857

[athens] sample 486/512: year=2040 aai=0.222

[athens] sample 487/512: year=2050 aai=0.236

[athens] sample 488/512: year=2020 aai=0.286

[athens] sample 489/512: year=2030 aai=1.484

[athens] sample 490/512: year=2040 aai=0.872

[athens] sample 491/512: year=2020 aai=3.831

[athens] sample 492/512: year=2030 aai=1.454

[athens] sample 493/512: year=2040 aai=2.419

[athens] sample 494/512: year=2020 aai=2.189

[athens] sample 495/512: year=2040 aai=3.915

[athens] sample 496/512: year=2020 aai=0.058

[athens] sample 497/512: year=2050 aai=1.407

[athens] sample 498/512: year=2030 aai=6.977

[athens] sample 499/512: year=2020 aai=0.436

[athens] sample 500/512: year=2050 aai=3.307

[athens] sample 501/512: year=2040 aai=1.321

[athens] sample 502/512: year=2050 aai=0.063

[athens] sample 503/512: year=2040 aai=3.321

[athens] sample 504/512: year=2020 aai=0.083

[athens] sample 505/512: year=2030 aai=0.281

[athens] sample 506/512: year=2030 aai=0.510

[athens] sample 507/512: year=2040 aai=0.172

[athens] sample 508/512: year=2040 aai=1.875

[athens] sample 509/512: year=2040 aai=0.367

[athens] sample 510/512: year=2030 aai=0.130

[athens] sample 511/512: year=2040 aai=2.116

[athens] sample 512/512: year=2030 aai=0.132

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))
/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

/opt/anaconda3/envs/urbanheat/lib/python3.10/site-packages/SALib/util/__init__.py:274: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  names = list(pd.unique(groups))

{'samples': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/unc_samples_athens_improved.csv'),
 'impact': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/unc_impact_summary_athens_improved.csv'),
 'freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/unc_freq_curve_athens_improved.csv'),
 'cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/unc_cba_ews_athens_improved.csv'),
 'vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/unc_vulnerability_athens_improved.csv'),
 'sens_aai': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/sens_aai_agg_athens_improved.csv'),
 'sens_freq': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/sens_freq_curve_athens_improved.csv'),
 'sens_cba': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/sens_cba_ews_athens_improved.csv'),
 'sens_vuln': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/sens_vulnerability_athens_improved.csv'),
 'meta': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/uq_dimensions_athens_improved.json'),
 'bundle': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/unc_impact_athens_march2026_improved.h5'),
 'bundle_sens': PosixPath('/Users/armandeaboudrar-meda/Desktop/CMCC/URBADAPT/urban-heat/outputs/athens/tables/uncertainty_improved/unc_impact_athens_march2026_improved_with_sensitivity.h5')}

In [3]:
import pandas as pd

samples = pd.read_csv(paths['samples'])
samples[[
    'year', 'aai_agg', 'annual_deaths', 'sample_warning_days',
    'sample_threshold_deaths_per_day', 'ews_pv_cost_25y',
    'ews_net_avoided_deaths_25y_cum', 'ews_cost_per_net_death_25y_cum'
]].head(10)

,year,aai_agg,annual_deaths,sample_warning_days,sample_threshold_deaths_per_day,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_cost_per_net_death_25y_cum
0,2050,4.915655,1794.214106,64.0,13.425055,3.757305e+06,1201.584694,3126.958132
1,2030,1.529789,558.372974,46.0,5.541310,3.196097e+07,1384.112904,23091.301245
2,2040,3.209911,1174.827363,33.0,13.123227,1.713465e+07,475.441372,36039.455607
3,2020,0.118619,43.414736,23.0,0.737606,1.791043e+07,132.580144,135091.363951
4,2020,4.720875,1727.840422,30.0,17.193208,4.342157e+06,5874.152266,739.197293
5,2030,1.041356,380.095053,28.0,4.761446,2.051614e+07,135.100236,151858.649755
6,2040,1.929573,706.223779,71.0,6.004856,3.885622e+07,1697.303776,22892.905870
7,2050,0.236746,86.412115,53.0,0.478667,2.324549e+07,178.353499,130333.790717
8,2020,2.275707,832.908583,23.0,11.391001,2.059946e+07,780.435136,26394.833436
9,2040,1.741154,637.262341,28.0,8.774112,1.494258e+07,1267.538992,11788.653278

In [4]:
impact_summary = pd.read_csv(paths['impact'])
cba_summary = pd.read_csv(paths['cba'])

display(impact_summary.describe())
display(cba_summary.describe())

,aai_agg,annual_deaths,rp2,rp5,rp10,rp20
count,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000
mean,1.588937,580.758895,0.100659,3.223408,5.547216,7.300354
std,1.592945,582.192080,0.290335,3.741725,5.281227,6.443588
min,0.039747,14.547562,0.000000,0.015100,0.180586,0.246544
25%,0.407850,149.116486,0.000000,0.489474,1.499599,2.221849
50%,1.009338,369.417705,0.000000,2.026018,3.812413,5.140500
75%,2.279001,833.739221,0.028310,4.871842,8.076976,10.417151
max,9.238710,3381.367842,2.156593,22.615738,28.958688,33.232271

,ews_pv_cost_25y,ews_net_avoided_deaths_25y_cum,ews_net_avoided_deaths_25y_pv,ews_cost_per_net_death_25y_cum,ews_cost_per_net_death_25y_pv,ews_life_years_saved_25y_cum
count,5.120000e+02,512.000000,512.000000,5.120000e+02,5.120000e+02,512.000000
mean,1.310753e+07,621.504826,406.248472,7.798249e+04,1.195859e+05,7892.015917
std,1.038603e+07,779.487849,508.255992,1.863592e+05,2.858069e+05,10007.933779
min,2.072302e+06,7.405444,4.665564,7.391973e+02,1.135906e+03,84.343688
25%,3.311700e+06,157.409134,102.335708,9.412110e+03,1.429677e+04,1955.114604
50%,9.988313e+06,341.448425,223.781641,2.460623e+04,3.737134e+04,4350.783162
75%,2.214435e+07,798.744568,524.839600,7.125020e+04,1.080335e+05,10064.200733
max,3.885622e+07,5874.152266,3822.638994,2.239224e+06,3.444111e+06,74482.828158